### ISSUE TITLE
debugging gbXML example 1

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#101]
I have this gbXML which is almost good. gbXML works when I remove this space. So what I did is opposite I extracted space that is causing issue. 
I noticed that when I load into gbXMLViewer we can not see surfaces on right had menu. 
This might be indication that something is wrong with file but no idea why. 

[gbXMLIssueSpace.zip](https://github.com/ladybug-tools/spider/files/1881915/gbXMLIssueSpace.zip)

![image](https://user-images.githubusercontent.com/14005893/38393107-b28aa312-3921-11e8-8ddb-fb60c39e970c.png)

**Comment by theo-armour** [comment]
@mdengusiak 

![image](https://user-images.githubusercontent.com/547626/38599996-6a9c46c4-3d17-11e8-9400-10a8154caf06.png)


## [gbXML Viewer R12.16]( http://www.ladybug.tools/spider/gbxml-viewer/dev )

HUD / Heads-Up Module
* If gbXML file has only a single space:
	* Formerly: displays blank HUD 
	* Now: displays relevant HUD data plus following message 'Model has only a single space, therefore there is no adjacent space data to be shown here.'
