### ISSUE TITLE
gbXML Viewer R13 Pre-Release Updates

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#102]
@ladybug-tools/gbxml-viewer-dev 

This issue is just to keep track of R13 updates in general. Specific issues with the release should be added as stand-alone issues - so they can be dealt with and closed.

## R13.3 ~ 2018-04-11

HUD /Head-up Display Module
* If gbXML file has only a single space:
	* Past: displays blank HUD
	* Now: displays relevant HUD data plus following message 'Model has only a single space, therefore there is no adjacent space data to be shown here.'

REP / Reports Module
* Element attributes starting to have buttons to update the display
	* Buttons for: ID, Surface type, Adjacent spaces, CAD object ID, Space and Zone
* Spaces report has zoom button

CSS / Style Sheet
* Better handling of sliding menus and pop ups on small devices
* Left menu needs more work

## R13.2
REP / Reports Module
* Very reorganized / all functions based on set and get
	* Should be more maintainable and extendable
* Variable and function names with clearer / more self-evident structure

Done: * 2018-04-02 ~ Update all get functions so they return objects

APP / Application Module

* Only a single Feature panel is visible at any given time
	* Multiple visible panels added complexity without much benefit

## R13.1
* Starting to have revision numbers
* REP / Reports Module
	Add 'Openings by Type' panel

ISS / Issues & Num / Numbers Modules
* Various fixes

HUD / Heads-Up Display Module
* Added and appears to be functioning OK
* Add the style theming to the window
* Streamline self-loading capability

Issue: Process of toggling the visibility of meshes, edges and openings needs streamlining.
* Often things that should be made visible when clicking around are not
* You need to click the 'all' button too often

## R13
* 2018-03-26:First Commit
* 2018-03-29: Multiple color themes and menu-toggles looking good
* 2018-03-31 ~ REP / Reports Module
	* New user experience
	* Display reports for all available attributes for surfaces, spaces, storeys, zones and openings
	* Add opening visibility toggle
	* Add 'Exposed to Sun' button
</details>

## R13 Objectives

* Seriously simplify GBP module << done
* Reorganized HTML element IDs and CSS style names so all items correspond to one another nicely
* Establish the Modules Explorer as the single source for access to features list, change log, support, links to GitHub source and read me, and more
* Continue adding items to Reports, Issues and Numbers
* Establish three sets of CSS styles for:
	* "Archie" the architect: all Pastels/ Looks Like Apple made it
	* "Cody" the coder: White text on black
	* "Inge" the ingénieure: All the colors imaginable

**Comment by theo-armour** [comment]
@mdengusiak 

R13.8: Heads-up display look and feel beginning to settle down

**Comment by theo-armour** [comment]
@mdengusiak 

R13.9
* Add first person camera module
* Add Sun path / Analemma module
* Add Sun Range Module

HUD
* Update Surface Type should now mostly be working
* Update Space and CAD Object ID in next release

Fingers crossed: R13 has a release candidate by this weekend

**Comment by mdengusiak** [comment]
@theo-armour 
I am starting first tests and will continue tomorrow... R13.9 lets see if we manage to get it for presentation :)
I am testing all click from top to the bottom all clicks on default model otherwise stated

**Features - Settings**
A. Settings visibility toggles
- works perfect!

B. materials settings
- works great
* only when I click Wireframe it seems that is constantly doing, please try on your PC

C. scene settings
- works perfect!

D. explode view
- works great just small item below
- When I explode space every click moves space right quite far....
![image](https://user-images.githubusercontent.com/26113670/39331460-901f12f0-499c-11e8-830b-0e126b762452.png)

E. section view 
- works AMAZING!! Really this is SUPER!

F.  Things to Try
- first person camera  - can not switch off, when is on works great!
- sun-path/analema - does not work for me
- sun-range it open but very slow ... this need to be improved in future is not critical right now, aslo I ca n not switch off and reset view does not complete reset after this one

**Reports**
A. Show || Hide / Zoom
- for _coventry-university-of-warwick-small.xml_ I can not see openings 

B. Select Report by Item
- this works great... jsut need to add now suppport for all openings type

C. Surfaces by Type »
- works excellent!

D. Openings by Type
- for _coventry-university-of-warwick-small.xml_ I can not see opening types

E. CAD Objects by Type
- works excellent!

F. gbXML
- correct

G. Campus Location
- correct

H. Building
- correct 
- including link to google map

**Comment by mdengusiak** [comment]
**Numbers**
A. Visibility Toggles
- works great

B. Areas by Storey
- ground floor is correct but when we have atrium level with air something is not perfectly matching 
- also I checked roof 2372m2 area and is about 172 m2 difference compare to revit values 2200m2
- raised floor is matching perfectly so we need to just review and better understand values

![image](https://user-images.githubusercontent.com/14005893/39386245-9fb39ac2-4a6b-11e8-85fe-54249cab5106.png)

![image](https://user-images.githubusercontent.com/14005893/39386311-f21a8d7a-4a6b-11e8-9bbc-496c2502749c.png)

![image](https://user-images.githubusercontent.com/14005893/39386151-1eca3498-4a6b-11e8-86e3-a025d2c6c123.png)

**Issues**
A. Visibility Toggles

B. Duplicate Coordinates 
- when clicking on space does not display
-delete does not work

C. Undefined CAD Object IDs
- this type of errors should logged here
![image](https://user-images.githubusercontent.com/14005893/39387252-7fad70b8-4a70-11e8-9641-182d6f0aaaf2.png)

D. Very Close Vertices by Id
- should have zoom

E.Opening Vertices  
- it does not wrok for me

F. Surface Type Invalid
- should have toggle all

G. Opening Type Invalid
- should have toggle all

H. Adjacent Space Invalid
- should have toggle all
- should have zoom

Can we add the same size of text to all Description Text
![image](https://user-images.githubusercontent.com/14005893/39387546-0fb544b4-4a72-11e8-829d-f3fd030f5d62.png)

**Right Menu**
A. Show || Hide / Zoom
- we can not any more hide one surface after selection click surface as in R12

aslo I would take layout from R12 works perfectly there very logical and organized
id:
Name: Panel-2894
surface type:
adjacent space id:
adjacent space id:
cad object id:

we missing area for building element
area 22.0 

lets add search to all including CADObjectID move update to top 
![image](https://user-images.githubusercontent.com/14005893/39388097-6bc616d6-4a75-11e8-86e6-685a65584559.png)

**Comment by theo-armour** [comment]
## Reports
> for coventry-university-of-warwick-small.xml I can not see openings

Note says: Issue: only shows external doors

This will be fixed soon. Also you may need to zoom and pan to see the window,

> D. Openings by Type
> for coventry-university-of-warwick-small.xml I can not see opening types

I cannot reproduce - except for internal doors


## Numbers
> B. Areas by Storey

Calculating errors exactly and accurately is likely to be an ongoing project. We should start with simpler models.


### Issues

Too many issues to discuss with the Issues panel now that it's using the code in the new HUD.

These will take a day or so to fix most of the items so they mostly work well enough to be used but not necessarily perfected.

**Comment by mdengusiak** [comment]
@theo-armour 
we are now R13.15 lots of stuff is fixed now... 
so let's try to address few items:

1.  Do you think we could add section along different axis
at the moment w cut section along red axis. Could we allow user should we cut section along x,y or z (red, green or blue)?
![image](https://user-images.githubusercontent.com/14005893/39798058-dbb8b9aa-5356-11e8-9c46-ab1534818382.png)

2.  When I click twice I can not swtich off each Feature like Settings, Reports ...same as we have in R12
![image](https://user-images.githubusercontent.com/14005893/39798164-3f2e9b94-5357-11e8-9ffe-b0924b54b05e.png)

3. We lost important functionality. When I click surface on right hand menu it hides whole building and not selected element.
![image](https://user-images.githubusercontent.com/14005893/39798293-d884ea6e-5357-11e8-9877-b7bf7202396a.png)

**Comment by theo-armour** [comment]
AGV R13.17

> Do you think we could add section along different axis

Added cutting sections along Y and Z axes. Wish list: Add rotate section cuts around X-axis.


>When I click surface on right hand menu it hides whole building and not selected element.

Fixed

**Comment by theo-armour** [comment]
Is there anything in this issue that still needs looking at? Or can we close it and start fresh?

**Comment by mdengusiak** [comment]
@theo-armour 
Yes, lets start new one

I LOVE this SECTION CUT absolutely AMAZING!!!!!!!!!!
