### ISSUE TITLE
Update 2018-04-17 ~ gbXML Viewer R12.17 ~ new stable release

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#103]
@ladybug-tools/spiders 

## Full Screen:  [gbXML Viewer R12.17]( http://www.ladybug.tools/spider/gbxml-viewer "faster, better, cheaper" )

![image](https://user-images.githubusercontent.com/547626/38856137-7232b3f6-41da-11e8-8bf6-a205ee90426e.png)
_New stable release.Yay!_

### New features include:
* Faster, more bullet-resistent code
* Choice of user interface colors
* Many workflow simplifications
* Reports on more types of gbXML elements and attributes
* Added openings as displayable objects
* Added new issue finders
* Added new area and orientation calculations panel
* Operation on mobile devices improved
* Second pass at adding edit and save changes capability

**Comment by mdengusiak** [comment]
@theo-armour 
OK R12.33 stable, tested and released :)
