### ISSUE TITLE
R12 adjust `ExposedFloor ` , `RaisedFloor ` behavour

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#105]
When we assign and fix surfaces 
`ExposedFloor ` , `RaisedFloor `should behave as `Roof `so  there is no second adjacency. 

![image](https://user-images.githubusercontent.com/14005893/39014849-5dccfe7c-4413-11e8-9c06-7f47bd316329.png)

**Comment by theo-armour** [comment]
@mdengusiak 

See R12.22

**Comment by mdengusiak** [comment]
@theo-armour 
thanks a lot
we can now see this under Issue: `Adjacent Space Invalid`
