### ISSUE TITLE
R12 add seach box for CADObejctID in HUD

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#106]
We need to add search for CADObjectID.. it takes aaaages to assing correct one..
if we introduce search we can just type ElementID from the end

![image](https://user-images.githubusercontent.com/14005893/39015086-2912ee52-4414-11e8-8864-12cf1df74432.png)

**Comment by theo-armour** [comment]
@mdengusiak 

See R12.23

**Comment by mdengusiak** [comment]
OK
How to use it :  just type CADObject ID keep pressing on the list to below to see items and select one you need,

Most important is we can fix models now and assign correct CADObjectID
