### ISSUE TITLE
gbXML Viewer: saving changes R11 vs R12 

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#110]
@mdengusiak 

In gbXML Viewer R11 all changes are saved when you click the 'save edits' button

In R12 we moved over to a 'save changes' scenario so that changes could be applied multiple times to multiple updates. When we made this change, we did not realize that IDs change from update to update. And therefore saving changes was not really a workable concept.

Future releases may well get around this limitation, but for R13 I suggest we return to the simple R11 'save edits' workflow.

**Comment by mdengusiak** [comment]
@theo-armour 
lets monitor how R13 behave and if all changes are saved
