### ISSUE TITLE
App: Add Multiple selection

### ISSUE THREAD

**Issue by EK-CEL** [ladybug-tools/spider#113]
In my model for a number of spaces Roof surfaces have not been generated. Instead there are the Air surfaces there. Currently I pick one surface, go to "heads-up" and change the "update" and "cad object id" there. Then I pick another surface, and so on. It is very time consuming for hundreds of the model issues I have.

1. I want to select a number of surfaces with traditional technique: hold Ctrl to add elements to selection and hold Shift to deselect elements.
2. I would like to have even more functionality: select elements with window. For example, I have many "Exterior Walls" inside the building. I want to select all of them with a selection window similar to Revit or AutoCAD.
3. It would be nice to have a Match tool. I would just select an sample surface and spread its properties to the selection.

Thank you.
E.K.

**Comment by theo-armour** [comment]
@EK-CEL 

Three excellent wish list items. Thank you!

I have added these to the current wish list:

https://www.ladybug.tools/spider/index.html#pages/gbxml-viewer-support-issues-wish-list.md

BTW, this list really needs updating as well, because a number of the items have been dealt with
