### ISSUE TITLE
REP: Lock toggles 

### ISSUE THREAD

**Issue by EK-CEL** [ladybug-tools/spider#114]
Here is my workflow for reviewing my gbXML models: 
1. I usually focus on Roofs, Exterior Walls, and Windows. I can hide unwanted things with the 'Surfaces' toggle.
2 . Then I review the my surfaces Storey-by-Storey. 

The problem is when I select a Storey the viewer resets my 'hidden' surfaces. I should re-assign my Surfaces visibility. It is not convenient.

I would like to be able to "lock" the Surface toggle visibility setting, and go through storeys. 
So, we need a various combinations of toggles' settings. We should be able to lock\unlock a toggle. If it is 'locked' it applies its settings to view, if 'unlocked' - on view update it shows all elements under the toggle.

Thank you,
E.K.

**Comment by theo-armour** [comment]
@EK-CEL 

All good suggestions worth discussing.

Several thoughts:

Work is well underway for R13 which changes many UI elements. See

http://www.ladybug.tools/spider/gbxml-viewer/dev

There are currently issues with toggling the visibility of items in the current pre-release. Also we just started adding openings as objects. Openings will need a release or two more before they settle down

Once some of those issues settle down, then let's tackle this one. One thing we could do is have a button that sets only exterior surfaces with openings as visible - or whatever works best with your work flow. The goal should be to get whatever needs to be visible for typical workflows - with a single click.

**Comment by EK-CEL** [comment]
@theo-armour 
Thank you for the comment.
I would like to share my typical techniques in reviewing a gbXML model. Hope it would be informative for the Spider development.
I am using the FZKViewer. Please watch the video here https://www.screencast.com/t/xeAlLLVto
It has some nice features:
*

**Comment by mdengusiak** [comment]
@EK-CEL 
Hi,
I was using FZKViewer as well. It is second free viewer I am aware of so  it is great alternative. I always struggle with zoom. 
 
We are working on new version that will have already some feature you mentioned so we can display each data in different way
![image](https://user-images.githubusercontent.com/14005893/40004175-0c2f0f64-578d-11e8-85c6-a6f6f60c6e0f.png)

windows are not yet present in R12 but will slowly get introduced in R13

We already  can see views per Storey and aslo Surface by Type  in slightly different way in Aragog. 

![image](https://user-images.githubusercontent.com/14005893/40004798-5d72abdc-578e-11e8-9cc6-c007a788d6e3.png)

**Comment by EK-CEL** [comment]
@mdengusiak 
Hi,
It is nice to see we are on the page with the FZKViewer :-).
And thank you for sharing the method of displaying the element's name instead of ID.
