### ISSUE TITLE
REP: Add "eye" for all categories

### ISSUE THREAD

**Issue by EK-CEL** [ladybug-tools/spider#115]
This is a feature request related to the issue #114 .
I see very nice and convenient 'eye' button for the Surfaces toggle. 
![image](https://user-images.githubusercontent.com/39136340/39838541-aa360454-53a7-11e8-94ed-4142b604fe6d.png)

It would great to have such visibility switch for every toggle in the 'reports'.

Thank you,
E.K.

**Comment by theo-armour** [comment]
@EK-CEL 

See my comments to #114

**Comment by theo-armour** [comment]
more visibility toggles are starting to be added throughout
