### ISSUE TITLE
rad viewer 10 ~ 2018-05-23

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#118]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/39859077-78263f74-53ed-11e8-9e93-e543f992dcec.png)

## [Source code]( https://github.com/ladybug-tools/spider/tree/master/solar-well/radiance-data-files )

* Handles polygons with any number of vertices
* Adds opacity slider
* Adds edges and edges toggle
* Add link to sample files

**Comment by theo-armour** [comment]
@ladybug-tools/spiders 

## full screen: [rad viewer 6]( https://rawgit.com/ladybug-tools/spider/master/solar-well/rad-viewer/rad-viewer-6.html )
![image](https://user-images.githubusercontent.com/547626/39987152-c5fba59e-5718-11e8-82c6-f9d633f9f367.png)

* Open files using file dialog box
* Open files via URL as a location.hash string
* Links to nine sample files
* Now ignores geometry it does not know how to draw

There are still a number of geometry primitives to be added. Once these are completed then materials will start to be added

![image](https://user-images.githubusercontent.com/547626/39987305-3724f9b4-5719-11e8-817d-5f4e8d12e6f4.png)

**Comment by mdengusiak** [comment]
@theo-armour 
It get better with recognition `london-office.rad`... only few more to solve and we get perfect geometry in RAD :)

**Comment by theo-armour** [comment]
@ladybug-tools/spiders 

## [rad viewer 8]( https://rawgit.com/ladybug-tools/spider/master/solar-well/rad-viewer/rad-viewer-8.html )

![image](https://user-images.githubusercontent.com/547626/40212743-77c0490c-5a06-11e8-8f6a-c33916004ceb.png)

* Adds very basic color rendering - plastic only - no specular, no sky and no lights etc yet
* More demo files added from gjward1
* Improved data parsing

![image](https://user-images.githubusercontent.com/547626/40212835-0aefad58-5a07-11e8-8f81-22fd81643e16.png)

**Comment by mdengusiak** [comment]
@theo-armour 
absolutely great!

**Comment by mostaphaRoudsari** [comment]
@theo-armour, This looks great! I can see that it fails to create the polygons with holes. That's a common practice in radiance that we should take care of it at some point.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

>  I can see that it fails to create the polygons with holes.

Ha ha! This is computer graphics - a topic certainly full of holes.

Actually Radiance polygons do not support holes.

From: http://radsite.lbl.gov/radiance/refer/refman.pdf

> Polygon
> A polygon is given by a list of three-dimensional vertices, which are ordered counter-clockwise as
> viewed from the front side (into the surface normal). The last vertex is automatically connected to the first. Holes are represented in polygons as interior vertices connected to the outer perimeter by coincident edges (seams).

In other words Radiance does not draw holes it just pretends to draw them. Radiance always triangulates the entire boundary. If, however, you draw your boundary very carefully it looks as if there is a hole.

For the most part Three.js Shapes can do this too. But the Shape geometry also supports actual holes. So it puts a condition on the drawing direction. It asks you to draw the Shape clockwise or counterclockwise.

Looking at the Radiance examples that I have, I see that with some geometries both the outside and the 'hole' are both drawn in the sane direction and other geometries even in the same example, the outside is drawn in one direction and the inside is drawn in the opposite direction.

Here is a graphic example of what I am seeing:

![image](https://user-images.githubusercontent.com/547626/40273663-7db0cdae-5b79-11e8-8f51-9d9c8c367b6e.png)

Here is an example of a wall where the lower surface with two openings is turned into multiple triangular faces and the upper surface with one opening is rendered as one polygon with a fake hole.

![image](https://user-images.githubusercontent.com/547626/40273809-9fddbeca-5b7c-11e8-8145-f4a37562f6ee.png)

I think I am going to have a jolly good time trying to fix this one.

**Comment by theo-armour** [comment]
So it looks like the Radiance polygons where the false openings occur may be identified because they have ten or more vertices and at least two pairs of vertices are duplicates.

![image](https://user-images.githubusercontent.com/547626/40274267-550e8248-5b87-11e8-999e-751e1811193c.png)

The interesting thing is that sometimes the Three.js shapes are two overlapping triangles and sometimes two overlapping rectangles and sometimes they are drawn correctly.

**Comment by mostaphaRoudsari** [comment]
@theo-armour, as usual you're making progress faster than what I can keep up with. :)

Yes. They will always have two pair of duplicate vertices. Here is a sample that shows how a polygon is structured:

![exported_300](https://user-images.githubusercontent.com/2915573/40280635-db49dd9c-5c24-11e8-8be3-a4d3f4d95c4a.gif)

> The interesting thing is that sometimes the Three.js shapes are two overlapping triangles and sometimes two overlapping rectangles and sometimes they are drawn correctly.

Not sure how you triangulate them but if you're picking every three vertices it is most likely because different polygons have different starting point.

Does THREE.js support creating planar mesh from a closed polygon?

**Comment by bwelle** [comment]
Actually sometime they will not have overlapping vertices. For example our rad files won’t. We will using antimatter to define polyloops.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mostaphaRoudsari** [comment]
@bwelle , that is a different case which won't be part of this issue. In that case the parent surface will be a surface and openings with antimatter material will show up as surfaces which will overlap with the parent surface. We're discussing problematic polygons with holes that follow this definition:

> Holes are represented in polygons as interior vertices connected to the outer perimeter by coincident edges (seams).

**Comment by theo-armour** [comment]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/40403755-c410e8ec-5e08-11e8-99ff-d129501c3bba.png)

## full screen: [rad viewer 9]( https://rawgit.com/ladybug-tools/spider/master/solar-well/rad-viewer/rad-viewer-9.html )

* Draws 'holes' correctly
	* Uses _ad hoc_ rules to reorder vertices
	* Appears to display the geometry of all the examples provided in the menu as expected (but may not complete on very large files )
	* Maintains reasonable speed

If the display of the geometry is not working for you, kindly send a link to a file that exhibits the issue.

@mdengusiak 

What are program are you using to create your Rad files?

**Comment by mdengusiak** [comment]
@theo-armour 
this is ABSOLUTELY AMAZING!!!!!
Viewer is now  fully solved for my all projects!!! THANKS

All my files are from:   Revit - gbXML  - Honeybee  - Radiance 
few old one link `warwick / hour-13-0.rad` where from Revit - Rhino - Radiance

I have now idea... do you think we could now see if some additional vertices can be removed and therefore surfaces simplified. Here we can see clearly that most of facade looks great only few parts causing issues?
![image](https://user-images.githubusercontent.com/14005893/40410829-9c23c44a-5e66-11e8-9de4-695d9a7c2d30.png)

**Comment by theo-armour** [comment]
@mdengusiak 

I'm happy you are happy

> do you think we could now see if some additional vertices can be removed and therefore surfaces simplified

Why not just just press the 'toggle edges' button? Perhaps edges display off should be the default.

**Comment by theo-armour** [comment]
![image](https://user-images.githubusercontent.com/547626/40460548-26997426-5ebc-11e8-96dc-d184d8cddb6b.png)
_Radiance RAD files with PTS data added as white-colored Three.js Sprites - all very work-in-progress_

## full screen: [rad viewer 10]( https://rawgit.com/ladybug-tools/spider/master/solar-well/rad-viewer/r10/rad-viewer.html )

* Rendering JavaScript extracted into separate file and namespaced ( made code safer and more reusable)
* Add ability to load and display PTS files with data displayed as Three.js Sprites
	* Reduce the opacity in order to view PTS data
	* Note: loading of RES files not yet supported

Working methods for associating PTS and RES data to the Three.js meshes is likely to be interesting. Just remember that Rome was not built in a day
