### ISSUE TITLE
write rad to json parser

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/spider#119]
@theo-armour,

I tested the viewer with a number of files and it fails to parse the files correctly in most of the cases. I think if I can write the parser and give you a ready to visualize json object you can concentrate on the visualizer which in many cases will be similar to the gbXML viewer.

I will put it together in python first and then we can convert it to JS. Haven't written code in JS for quite some time! Here is the schema that I'm thinking about.

```Javascript
{
  "geometry":[
      {"type": "polygon", "name": str, "vertices": [{"x": float, "y": float, "z": float}, ...]}, ... // we can add other geometry types later
   ],
   "modifier": [
        {"name": str, "type": str (glass/plastic/...), "values": str // full definition for visualization}, ...
    ]
}
```

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

I think the reason the current viewer is incomplete is because I have only four test files to work with.

See: https://github.com/ladybug-tools/spider/tree/master/radiance-sample-files

Also, I do not yet know how to identify failures.

For example: is there anything wrong with the geometry here:

![image](https://user-images.githubusercontent.com/547626/39949878-934e3158-5532-11e8-971f-5f4b0657809a.png)

In any case, links to more sample files would be of great benefit!

**Comment by theo-armour** [comment]
@sariths 

I had a quick run through your repos and found this one with .RAD files:

https://github.com/sariths/radTutorialFiles

Thank you for making this tutorial available.

Please do make more files available for testing.

**Comment by mostaphaRoudsari** [comment]
@theo-armour, both cases are loaded correctly. If it is possible to upload multiple files at the same time user can upload them together instead of you searching the directories.
@sariths, your sample files are going to be very helpful. I cannot share the ones that I used for testing since I don't own them! :| All the other models that I have are too simple.

**Comment by theo-armour** [comment]
See also #118 update with kink to Rad viewer r6

I have found a good amount of RAD files here:

http://radsite.lbl.gov/radiance/pub/objects/

I'm think of extracting all the files and putting them in a repo at Ladybug Tools. This would give easy online access to all the files from anywhere. Anybody have any thoughts on this?

**Comment by sariths** [comment]
@theo-armour , @mostaphaRoudsari 

Santa brings presents ...    https://github.com/rndmStff/radModels

I had been meaning to put some of these on a repo for a while. The instructions on the main page apply for all models.  

The data structure for most (if not all) radiance materials and geometry follow the format described on page 4 of [file-formats](radsite.lbl.gov/radiance/refer/filefmts.pdf). Some of my models contain textures and lights, both of which you can ignore. The list of surfaces can be found here: http://radsite.lbl.gov/radiance/refer/ray.html#Surfaces . It would useful to color the surfaces according to their [modifier materials](http://radsite.lbl.gov/radiance/refer/ray.html#Materials) . For commonly used modifiers, the colors are rgb triplets specified at the beginning of the numerical array. 

Finally, assuming that 3.js also follows some sort of global coordinate system like Radiance, it might be really useful to read-from and write-to view definitions like the ones provided in the view sub-directory for each project ([example](https://github.com/rndmStff/radModels/tree/master/TajWithLuminaires/views)). 

Please let me know, if you would like any further details.

![2018-05-14 12_08_21-c__users_sarith_appdata_local_temp_tmpvobxyprad_scene oct](https://user-images.githubusercontent.com/10361848/39995666-40a7d416-577d-11e8-818c-dd0c0b3573fb.png)
![2018-05-14 11_54_50-c__users_sarith_appdata_local_temp_tmplpr08frad_scene oct](https://user-images.githubusercontent.com/10361848/39995667-40c25fde-577d-11e8-9434-198d451b9f1c.png)
![2018-05-14 11_46_26-c__users_sarith_appdata_local_temp_tmpnizaecrad_scene oct](https://user-images.githubusercontent.com/10361848/39995668-40e276c0-577d-11e8-9625-697acf4eeedb.png)
![2018-05-14 12_58_58-c__users_sarith_appdata_local_temp_tmpkm8zxprad_scene oct](https://user-images.githubusercontent.com/10361848/39995669-41016198-577d-11e8-8120-a6598689e476.png)
![2018-05-14 12_53_29-c__users_sarith_appdata_local_temp_tmpkm8zxprad_scene oct](https://user-images.githubusercontent.com/10361848/39995670-4134b2f0-577d-11e8-84c0-5b4903def6d6.png)
![2018-05-14 12_39_06-c__users_sarith_appdata_local_temp_tmpn4bqrvrad_scene oct](https://user-images.githubusercontent.com/10361848/39995671-415413f2-577d-11e8-909d-be44fe38e4fd.png)
![2018-05-14 12_34_54-c__users_sarith_appdata_local_temp_tmpn4bqrvrad_scene oct](https://user-images.githubusercontent.com/10361848/39995672-4171f426-577d-11e8-8d8d-165a7c6445f5.png)
![2018-05-14 12_33_53-c__users_sarith_appdata_local_temp_tmpn4bqrvrad_scene oct](https://user-images.githubusercontent.com/10361848/39995673-419aa3ee-577d-11e8-99a4-11bf500901bc.png)
![2018-05-14 12_22_16-c__users_sarith_appdata_local_temp_tmpkz6zdzrad_scene oct](https://user-images.githubusercontent.com/10361848/39995674-41b4265c-577d-11e8-9c27-d9669c745bde.png)
![2018-05-14 12_18_37-c__users_sarith_appdata_local_temp_tmpfn_balrad_scene oct](https://user-images.githubusercontent.com/10361848/39995675-41d6ddb4-577d-11e8-8365-21ff5755d559.png)
![2018-05-14 12_10_11-c__users_sarith_appdata_local_temp_tmpvobxyprad_scene oct](https://user-images.githubusercontent.com/10361848/39995676-41f2a684-577d-11e8-9f74-aba2b656499d.png)

**Comment by sariths** [comment]
@theo-armour This is awesome (I am really awed)! 

There are have been a few Radiance object viewers in the past, but none of them are web-based or particularly stable. Even the ones which are desktop-based are not really cross-platform. The ones that I am aware of are [Glrad](http://radsite.lbl.gov/radiance/glrad.1.html), [Rshow](http://www.pab-opto.de/progs/rshow/) and [Objview](http://radsite.lbl.gov/radiance/objview.1.html) . I have never been able to get  Glrad to work and haven't tried tinkering with Rshow. Objview is actually a perl (earlier csh) script that is a pain to run on Windows. I wrote a Python version of [objview](https://github.com/gmischler/PyRad/blob/master/scripts/objview.py) and it is what I use for my own work.
However, the issue with all these viewers is that they focus on rendering Radiance scenes as-is and that is extremely time-consuming. A lot of times one is only interested in knowing if the import from CAD to Radiance was successful or not. Or, in some cases, assigning views for rendering scenes (or annual climate-based simulations). 
So, a stable version of rad viewer would be really useful for the community as a whole. 

PS: Things move at a (0.00001 x snails-pace) in the Radiance world. So, it will be a while before the community wakes up to the possibilities of such an tool.)  

PS2: I agree that the face-count is high and not optimized. I dont know much (any) CAD and most of these files where from when I was trying to learn Radiance.

**Comment by theo-armour** [comment]
@sariths @mostaphaRoudsari 

Have a look at #118. We have colors

![image](https://user-images.githubusercontent.com/547626/40214015-5bd6bde6-5a0d-11e8-9321-35e24d0a2d0c.png)

> So, a stable version of rad viewer would be really useful for the community as a whole.

The code needs another release or to two be cleaned up, but after that - or any time actually - I can take feature requests.

>  I agree that the face-count is high and not optimized. 

Going from a Sketchup export format and then to Radiance is definitely going to generate a ton of faces. But I don't think that will be the usual workflow. The files supplied by Mostapha and Michal are reasonable in size and load fast. So I don't expect many problems with this sort of workflow.

Let's make Radiance fun again. ;-)
