### ISSUE TITLE
R13 pre-release comments

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#120]
1. Spaces and storey are not working for me

![image](https://user-images.githubusercontent.com/14005893/40219964-772bf93c-5a6f-11e8-8052-fc52da135e7f.png)

2. Exposed to Sun is not displaying correctly
![image](https://user-images.githubusercontent.com/14005893/40220031-ad35b3ec-5a6f-11e8-8a7a-bd852c9357bf.png)

Please see attached test file,

[TestFile.zip](https://github.com/ladybug-tools/spider/files/2015776/TestFile.zip)

**Comment by theo-armour** [comment]
I note a lot of spaces in the various attributes, Could this be a problem?

I any case I cannot load the file in the browser, It crashes the browser before completing the load.

**Comment by mdengusiak** [comment]
Hmm ...I can load and works perfectly for me

**Comment by theo-armour** [comment]
> Hmm ...I can load and works perfectly for me

Loading in Aragog and loading in the browser are two very different actions. Did you try both?

For me loads in Aragog R13 but not in Chrome.

***

I see there is a space with title id="00_901 AHU_1_Ignore" The space is several hundred meters away from the main building. Is this an issue?

***

I note that there are 7970 SpaceBoundary elements with surfaceIdRef="".

Aragog does not read SpaceBoundary elements but this could be part of the issue, maybe

***
