### ISSUE TITLE
Rad Viewer R11

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#125]
@ladybug-tools/spiders 

## [Rad Viewer 11]( https://rawgit.com/ladybug-tools/spider/master/rad-viewer/r11/rad-viewer.html )
_London Office_

![image](https://user-images.githubusercontent.com/547626/40525949-2d732b3e-5f98-11e8-810c-5216fbaaeed6.png)

### Change Log
* Files forked to top level folder
* Add ability to load RES Files
* Add two hard-wired demos: 'London Office' and 'Bristol Clifton Downs'

### Issues
* Has trouble with files loading asynchronously. 
    * You may need to load the page and files more than once. If not loaded well then shading will be in splotches. After files are settled in your cache things should start to look right. 
* You will need to reload the page in between the two hard-wired demos in order to erase previous geometry
* And still many other issues.

### Comments

I don't have Revit, Rhino, Grasshopper or Honeybee. I have never used Radiance. The Radiance manual has no illustrations. I have no colleagues that play with Radiance.

So this is pretty much the first time I've experienced what Radiance does. OK I did have a glimpse of Chris effort during the webinar and Hydra has some images. But up to now I've had no idea what all the dozens of Radiance files are doing, let alone what the data looks like.

The goal of this project is to be able to get non-professionals and newbs familiar with Radiance. Guess what? Newb #1 that's learning is me!

@mdengusiak thank you for the Radiance results files. I could not be proceeding without these.

![image](https://user-images.githubusercontent.com/547626/40525994-7a67b0cc-5f98-11e8-8b7a-11a0e3827de8.png)
_Bristol Clifton Downs_

**Comment by mdengusiak** [comment]
@theo-armour  this is absolutely great. Next step must be loading rad + *.pts + *.res files. So we can start testing models.

**Comment by theo-armour** [comment]
@mdengusiak 

## Link you can use for latest stable version: <https://www.ladybug.tools/spider/master/rad-viewer/>

***

## full screen: [rad viewer 12]( https://www.ladybug.tools/spider/master/rad-viewer/r12/rad-viewer.html )

* Adds capability to read multiple files from a local folder
	* Files must be set up as or as if exported from Honeybee - see image below

![image](https://user-images.githubusercontent.com/547626/40633462-bb33c9c4-62a4-11e8-860c-b8d76ae3a418.png)


## Issues

* 2018-05-28 ~ shadow points not deleted when a new model is loaded. Must reload page to erase

**Comment by mdengusiak** [comment]
@theo-armour  Absolutely Amazing! let me think and test on few items before new comments :)

thanks a lot!

**Comment by theo-armour** [comment]
@mdengusiak 

Note: all files must be loaded at the same time. You may user control/command-A to select all the files.
