### ISSUE TITLE
gbXML Viewer Basic ~ a new script

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#129]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/40881609-f5ff21aa-667f-11e8-8de7-54a5c4438552.png)

## Concept

The ['Aragog' gbXML Viewer]( http://www.ladybug.tools/spider/gbxml-viewer/r13/gv-app-application/gv-app.html ) is a nice bit of work - or it will be one day - but the code base is getting lengthy and convoluted. It's no longer a place for beginners to start. You can't just open it up and see what's going on in fifteen minutes or so.

Therefore we now have gbXML Viewer Basic

This is a very basic gbXML file viewer
* Use this code if you want a the basic idea of how to read a gbXML file and turn it into a Three.js scene
* Use this code if you want to learn how to take sets of coplanar points and convert these to Three.js 2D Shapes with holes - all positioned and rotated arbitrarily in 3D space.

The intention is that the core gbXML parser here and the core parser in the full-featured gbXML Viewer and the parser in the RAD Viewer all contain identical or nearly identical code.

The code should be simple, fast and easy to read. If you can read and understand the Three.js examples and the [Mr.doob coding style&trade; ]( https://github.com/mrdoob/three.js/wiki/Mr.doob's-Code-Style%E2%84%A2 ), then you should feel at home here. Be prepared to enjoy the white space!

A good function to look at is ```GBX.get3dShape()```. This function takes a set of 3D coplanar points along with points that bound any holes and converts these into a Three.js mesh bounded by those points. This mesh is created using a Three.js Shape - which is excellent stuff but very 2D. The conversion requires that you conjugate your quaternions and do all manner of other unreal linear algebra thinking. All this in just 300 or so lines of code.

The gbXML portions are also interesting. The routines end up with three sets of data for every element in the original file: XML, JSON and Three.js meshes.

## Issues

* 2018-06-02 ~ Theo ~ Need a spider name - preferably one without a trademark, perhaps a nice-sounding latin name: https://en.wikipedia.org/wiki/List_of_spider_common_names
* 2018-06-02 ~ Theo ~ currently surfaces, edges and opening are each their oen group of objects. Could nicer things happen if the edges and opening were children of their parent surface??

**Comment by mdengusiak** [comment]
@theo-armour
great idea

1. We need some basic and alone 'type' of spider
`Widow spiders`

COMMON NAME: Black Widow Spiders
SCIENTIFIC NAME: Latrodectus

**Comment by afomi** [comment]
@theo-armour - I think this release is out there. Is there anything keeping this Issue open?

I'd like to better understand how gbXML Viewer relates to Aragog. - It seems like a subset of features. If that is the case, is the intention to package and distribute the basic Viewer as a standalone?
If so, then we can consider making the API a bit more explicit and tailoring code examples around it.

**Comment by theo-armour** [comment]
All further discussion should take place in the new repo:

### https://www.ladybug.tools/spider-gbxml-tools/
