### ISSUE TITLE
Update parser to read in different coordinate ordering for walls.

### ISSUE THREAD

**Issue by bwelle** [ladybug-tools/spider#131]
Working wall coordinates are:
grey_0.6 polygon ExteriorWall.surface-21
0
0
30
    -15.240000  15.240000  0.000000
    -15.240000  15.240000  3.048000
    15.240000  15.240000  3.048000
    15.240000  15.240000  0.000000
    10.159898  15.240000  0.381000
    -10.159898  15.240000  0.381000
    -10.159898  15.240000  2.667000
    10.159898  15.240000  2.667000
    10.159898  15.240000  0.381000
    15.240000  15.240000  0.000000

Not working coordinates are:
grey_0.6 polygon ExteriorWall.surface-21
0
0
30
    15.240000  15.240000  0.000000
    10.159898  15.240000  0.381000
    -10.159898  15.240000  0.381000
    -10.159898  15.240000  2.667000
    10.159898  15.240000  2.667000
    10.159898  15.240000  0.381000
    15.240000  15.240000  0.000000
    -15.240000  15.240000  0.000000
    -15.240000  15.240000  3.048000
    15.240000  15.240000  3.048000

File with not working coordinates in test-case-1 directory. Named as such. Both these orders are valid in Radiance.

**Comment by theo-armour** [comment]
@bwelle 

This issue needs several sample files from the same source so we can assure that the fix works for all files from the given source.

One day, we should have code that will build the correct surface no matter the order of the coordinates.

But for now - in the still early stages of things - it is better to build code based on a custom code for each source of the .rad files.
