### ISSUE TITLE
More info needed: SPEED Rad2Solar Viewer Read Me

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#132]
@bwelle 

See: [SPEED Rad2Solar Viewer Read Me]( https://github.com/ladybug-tools/spider/blob/master/sandbox/speed-rad2solar-viewer/README.md )

Which of my (too many to count) scripts are referring to?

There are two files for SPEED that your comments could refer to:

[Rad Viewer 12 Speed]( http://www.ladybug.tools/spider/rad-viewer/r12-speed/rad-viewer.html )

[Rad Viewer Bitmap R3.1 Speed]( http://www.ladybug.tools/spider/rad-viewer/rad-viewer-bitmap/r3-speed/rad-viewer-bitmap.html )

But I guess, we can sort these things in detail out once we have either bitmaps or point data SPEED sample files to work from.

**Comment by bwelle** [comment]
All specs refer to R3.1 SPEED. That’s all we will use from now on.

-----------------------------------------------------------------------------------------------
Benjamin Welle, PhD, PE, LEED AP BD+C
Director of Energy Lab
Nicollett Mall, IDS Center, 80 S 8th St #300, Minneapolis, MN 55402
t 415.856.3000 m 858.344.6858 benjamin.welle@perkinswill.com<mailto:benjamin.welle@perkinswill.com>

Perkins+Will  Ideas + buildings that honor the broader goals of society
perkinswill.com<http://www.perkinswill.com/>|Blog<http://blog.perkinswill.com/> | Facebook<http://www.facebook.com/ideasandbuildings> | Twitter<http://www.perkinswill.com/pages/twitter.html>

**Comment by afomi** [comment]
@theo-armour - What's the goal of this Issue? Is there something regarding updating a README?

@bwelle references the Speed R3.1 as the desired way forward.
