### ISSUE TITLE
R14  - add types to left menu surfaces

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#133]
@theo-armour 
Can we add like per R12:
- `type `for all gbXML types so we can make quick change

![image](https://user-images.githubusercontent.com/14005893/42021803-7bf3c1d4-7ab3-11e8-98fc-9647532687db.png)

**Comment by theo-armour** [comment]
@mdengusiak 

updated

![image](https://user-images.githubusercontent.com/547626/42237433-964fa37e-7eb2-11e8-9e3d-f07b3003a9c4.png)

**Comment by mdengusiak** [comment]
thanks
tested and approved :)
