### ISSUE TITLE
R14 - display opening type

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#135]
@theo-armour 
implement same scheme for `opening type` as we have for `surface type`
so we can change and assign different type

![image](https://user-images.githubusercontent.com/14005893/42022382-211091dc-7ab5-11e8-8ffe-57a4dfa5cab6.png)

**Comment by theo-armour** [comment]
@mdengusiak 

Added to Context menu wish list

https://www.ladybug.tools/spider/#gbxml-viewer/r14/gv-ctx-context-menu/README.md

**Comment by theo-armour** [comment]
@mdengusiak 

Hide surfaces
Show Openings
Click on any opening
View details of the selected opening in the context menu

![image](https://user-images.githubusercontent.com/547626/42239026-8a27f07e-7eb7-11e8-8f07-083e47298541.png)

**Comment by mdengusiak** [comment]
@theo-armour 
this is nice starting point we need to try to get same approach as we have with surfaces. So we can select zoom, hide and change type..etc

**Comment by theo-armour** [comment]
@mdengusiak 

Added to wish list

https://github.com/ladybug-tools/spider/tree/master/gbxml-viewer/r14/gv-sel-select-attributes
