### ISSUE TITLE
Aragog basic R5.2  for Openstudio  2.6.1

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#144]
Would be good to review our basic viewer. I tired to load our standard file but recieved this warning

![image](https://user-images.githubusercontent.com/14005893/45387319-9bd41e00-b60d-11e8-8e20-9e8c1a2fd9d2.png)

I can see it is loading into Aragog full version

![image](https://user-images.githubusercontent.com/14005893/45387404-e48bd700-b60d-11e8-99c6-ef770257daf6.png)

Please see attached file
[OpenstudioTest_1.zip](https://github.com/ladybug-tools/spider/files/2372717/OpenstudioTest_1.zip)

**Comment by theo-armour** [comment]
@mdengusiak 

Issues for the Spider gbXML Viewer Basic should be raised in it's repo:

https://github.com/ladybug-tools/spider-gbxml-tools/issues

**Comment by mdengusiak** [comment]
moved to correct repo
