### ISSUE TITLE
Build Well Road Map

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#15]
@ladybug-tools/spiders 

This issue is for ongoing discussion regarding regarding the purpose, usage and development of Build Well.

As of this writing Build Well is being developed to help a particular firm develop its own particular use case. This is intentional and its mission. It would also be nice to envisage and build for other usages.

If nothing else, it is likely that some of this code will be part of a 'Room Well' or 'Space Well' project with Mostapha's guidance.

This issue is not a good place for discussion regarding issues with current releases. These should be discussed in the various issues under the 'Updates' label.

Any and all thoughts, comments and suggestions appreciated and welcomed.

**Comment by bwelle** [comment]
Thanks for starting this thread.

While you are correct in its intent and mission, you may make any code you develop for us open source. The process of taking building footprints and "pre-parameterizing" them for large parametric studies is a unique part of this tool that under normal circumstances, I would not make open source. This applies for for any visualization work we do for outputs (like the scatter plot zooming in to actual building designs, not just points). However, I understand how passionate you are for this end goal, and it's only fair to do so given the great work you are doing for us. I only ask you give credit to myself and Anton for contributing. How does that sound to you?

**Comment by theo-armour** [comment]
@bwelle @antonszilasi 

All sound good to me

I do hope we find a way of working together on 3D data viz while not breaching client privacy and not infringing on corporate competitive advantage.

In subsequent comments, now that Build Well is beginning to settle down a bit, you will see where I think Build Well is going. What I want to know from you is: what aspects need to be changed, enhanced explained or simplified in order to make a comparable Build Well effort usable in your work particular environment?

So, Anton, I think that a lot of this will rest on your shoulders. Please know that I am here to help. And, of course, the longer you wait, the faster, simpler and better the code becomes. ;-)

**Comment by bwelle** [comment]
Yes, it will be a tight rope re competitive advantage and supporting your open source initiative. My approach, specs and functionality I provide you are minimal critical path such that Anton can understand how to take it and run with it. And honestly, whatever is open source from work we do that could be picked up and used to reduce any competitive advantage from our platform will likely not take place on a timeline I'm concerned with.

**Comment by bwelle** [comment]
Though honestly again, it it was it wouldn't concern me. It serves as justification to request more funding to stay ahead of the pack.

**Comment by theo-armour** [comment]
https://greenspacelive.com run a project that appears to be similar to Build Well. It is titled 'Building Generator. Here's the link:

https://greenspacelive.com/site/building-generator/

Here's a screen shot:

![image](https://user-images.githubusercontent.com/547626/30836285-0a48581c-a212-11e7-93f1-2a07f650eec2.png)

You will note that at the bottom of the app there are buttons to export the data as gbXML files or IDF files. 

Therefore it seem logical to do the following

Offer data export in the following formats:

* Ben's very simple CSV schema
* gbXML
* IDF

It would also make sense to provide building shape generators that follow both Ben's suggestions and Green Space Live's shapes.

One interesting feature that Green Space Live offers is to be able to lock certain parameters. We should look into this ourselves. Ditto elevation variable WWR.

A nice aspect of this will be that we can generate models that may be used to test the GBXML viewer.

Of course, there's a huge number of other features that can be added, but does the above sound like a good list of thing to do now or next?

**Comment by bwelle** [comment]
"What I want to know from you is: what aspects need to be changed, enhanced explained or simplified in order to make a comparable Build Well effort usable in your work particular environment?"

I will give this detailed list tonight.

**Comment by bwelle** [comment]
That is quite similar in terms of geometry generation with a few key exceptions...no parametrics and greenspace stuff on the backend won't come close to what we will be able to do. And their visualization is shit.

**Comment by bwelle** [comment]
When I provide my list of critical path to-do's I will include some responeses to your comments above.

**Comment by bwelle** [comment]
Closing this issue for house keeping purposes.
