### ISSUE TITLE
exposedToSun - Should be automatic?

### ISSUE THREAD

**Issue by EK-CEL** [ladybug-tools/spider#153]
I had issues in my model, i.e. some Roof segments were defined as Air. I changed the surface type to Roof with the Spider. Then I clicked the Exposed to Sun button under the Revit > Surface by Type. And the Roof was not shown. I guess it happens because the exposedToSun property is still _false_, as it was for Air surface type previously. 
![image](https://user-images.githubusercontent.com/39136340/47659946-64451500-db6c-11e8-8dc7-7153618abe8a.png)

I expect that that value should change to _true_ as soon as I change the surface type to Roof of External Wall. And back to _false_ if it is not the mentioned surface types.

Thank you.

**Comment by theo-armour** [comment]
@EK-CEL 

Excellent suggestion. I will be adding this to next release of the viewer
