### ISSUE TITLE
2017-09-23 ~ Build Well R5.1 ~ 'When in Rome, do as the Romans do' Release

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#17]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/30778998-24de0120-a098-11e7-9645-3a2a927bd2e8.png)

## Source code: https://github.com/ladybug-tools/spider/tree/master/sandbox//build-well/

Though this is numbered as a point release, it turns out there was a huge interesting change.

In the CAD/CAM world the Z axis is up. In computer science the Y axis is up. The defaults in Three.js follow computer science, which normally is fine because nobody cares about axes for the most part. But in CAD/CAM, XYZ is of the essence.   

Up to now all the scripts in Spider have had Y as up. Until today.  If Spider scripts are to help CAD users then, Spider should do as the CAD users do. So R5.1 is a rebuild of Build Well with Z as up.

Technically it's just about adding one line of code:

    camera.up.set( 0, 0, 1 );

But mentally it is quite upsetting too. It turns your world on its side. ( I am not sure whether that is figuratively or literally. ;-)

Anyway a bunch of other nice things came in as well.

## Change Log

* Add some prettifying to mnu-site-context.html. 
* Z is the new up. X & Y now on the ground.
* L Shape is back but incomplete.
* Continued simplifying and standardizing across the scripts
* Shapes use center point of geometry as origin

***

@antonszilasi: are you receiving these messages?

**Comment by theo-armour** [comment]
@ladybug-tools/spiders 

##[Build Well R5.2]( http://www.ladybug.tools/spider/sandbox/build-well/r5/build-well.html )

See Read me for updates

**Comment by antonszilasi** [comment]
@theo-armour  yes I am receiving your messages, let me know if you have any questions!
