### ISSUE TITLE
Build Well Project Management

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#20]
### Deadlines
Ben has to show something cool to his peeps in November. So we should work backwards and see what need so to be done by when.

We want to get the visualization working for a Box, L shape for demo. Integration with GUI will take some time, but is critical path for ME work. Also deadlines for gbXML and 3D scatter plot. So let's try this for schedule...

This was the original schedule. I prioritized shape stuff since integration with MicroExcel was a concern...

Box-Shape- October 2nd
L-Shape- October 5th
Space/Zone Assignment- October 8th
gbXML-October 12th
3D Scatter Plot-October 18th

However, since you are focused on gbXML now, let's go with this...

gbXML-October 5-10th
Box-Shape- October 9th
L-Shape- October 11th
Space/Zone Assignment (viz, not gbXML)- October 13th
3D Scatter Plot-October 18th (want to discuss 2D view too, will send more info shortly)

### Various task areas

Remaining tasks for Box other than bug fixes of current release (noted in release notes):

1. Put x,y,z axis on the ground plan, make it black and thicker so it's very clear to the user visually, and put letters x,y,z on them. 3D text.

2. Add new window inputs and logic to place window arrays. I sent you what I have, let me know if you need more.

3. If user goes back and changes total building area, length and width update based on ratios of building areas.

4. Add N,S,E,W letters to view. Calculate based on angles so updates as rotate building. Make letters 3D.

5. Create 2D view somewhere that updates with 3D. Orthographic view like you said. Show equations in 2D text along building sides. When first show box, show equations on each side (Length 1 for x side and Width 1= (Building Area)/Length 1 for y side). Once user starts entering new values for independent parameter (Length 1) or changing parameters that change dimensions such as # of Floors, Building Area, we want to start showing actual numerical value rather than equations. Maybe make “Show equations” and “show values” a toggle the user can choose from!

###  Cameras

We need to switch seamlessly between three types of cameras
* Perspective - usual god-mode 3D view
* Orthographic - 2D-like views
* Fly-through - to inspect projects from the inside

BW-I don't think fly through is critical path now. They can zoom in if they want.

This will take a day or two to prepare some demos and see if acceptable

### Text

Text is 3D has a number of interesting qualities
* Normal 2D text is difficult to read when you look from behind. And looking from behind is where you usually are.
* 3D text is neat but require hundreds of triangles to produce which can really slow things down - and you still end up looking from behind

Anyway, I will prepare some demos of possibilities

### Debugging & Github

There's a lot to be done to get everybody up to speed on using GitHub effectively and being able to report errors effectively. I will be posting about both of these aspects.

### gbXML

This looks like being the next big push: Getting Build Well to export its data in beautiful, clean gbXML.

Here is a personal issue: I do not download, install or compile ever. So would it be possible to build an online gbXML validator?

Something like
* http://jshint.com/
* http://jslint.com/
* https://jsonformatter.curiousconcept.com/

More immediately, I will need guidance in the naming and cataloging of every aspect of Build Well as it relates to gbXML. Perhaps we should start with a demo file and I try to get the exporter to match it.

Chien Si mentions 'We have prepared a very simple gbXML description that meets these minimum requirements.' but I've not yet discovered which file that is.

BW- Anton can help with this. You saw what Chien Si sent you. Not sure if that C# format is easily integrated. The gbXML functionality is less important now than getting the three.js stuff for the three shapes working.

### Current Help Wanted

* Area/Length/Floor calculator for L shape, Ben can you post details as an issue? 

BW-yes I will do this today.

* Currently, I don't happen to have any Apple products to test on. So hearing that things work on a Mac would be cool.
* The main thing to look at now is entering data in the various data input boxes and pushing to extremes or entering bad data. Fastest way is to use tab keys to jump between boxes and the to use up/down cursor keys to update values. if you can reproduce an issue - describe which box and what data was entered - please report.

BW-Will do.

**Comment by bwelle** [comment]
Thank you for starting this thread, it is time for this. Getting your work integrated with our GUI that MicroExcel is doing is of the highest priority now in terms of them being able to meet our deadline. There are uncertain about that integration. I proposed we get the Box shape to where it needs to be, then if you are willing to, hop on a call with MicroExcel, Anton, and myself to discuss the software architecture give them a helping hand in getting them going integrating with the GUI.

**Comment by bwelle** [comment]
Re gbXML, I will try to ask Chien Si for more guidance. He's already tapped out on other stuff for this project, so not sure how much of his time I can get.

**Comment by bwelle** [comment]
Issue to contemplate....In our web GUI, the user will be able to toggle between IP and SI units. If they use SI, can your code be modified to use it? If they are entering info in, and right in the middle toggle to SI from IP, could this be accommodated, or is it pick system, and stick with it?

**Comment by bwelle** [comment]
Ok spoke with Chien Si. When you are ready, he will hop on a call with the three of us re gbXML and how to get started on Git.

**Comment by bwelle** [comment]
Maybe we can get a head start with getting ME familiar with how to integrate. The adjacent building stuff is done. Could you post a version of the code with only that part so I can send to ME and they can start with just that part? Or can we do that with the current code?

**Comment by theo-armour** [comment]
All code here:

https://github.com/ladybug-tools/spider/tree/master/sandbox/build-well/

with source code in each 'r' folder

So in this case:

https://github.com/ladybug-tools/spider/blob/master/sandbox/build-well/r7/mnu-adjacent-buildings.html

**Comment by bwelle** [comment]
I just realized that for the gbXML export for Build Well we have a few more pieces of information we need to integrate from the web GUI. Specifically, we have a place where we assign Space Names to specific Zones (same as spaces for us). This information is required for gbXML export. I'll provide more detail shortly.

**Comment by bwelle** [comment]
Closing and opening new updated Build Well PM issue.
