### ISSUE TITLE
Update ~ 2017-09-28 ~ Build Well R7

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#21]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/31001886-d70fbe4a-a49b-11e7-8b05-28615ba664b2.png)

## Change Log

The menu system is more robust, enables the display of Markdown format files and enables switching menu items without losing data.

It will also facilitate the development and display of the JSON and gbXML export capabilities

* R7
* Menu and file handling rebuilt
	[x] 2017-09-23 ~ Better handling of data when switching tabs after a shape has been created
[x] 2017-09-21 ~ See if perimeter depth diagonals actually add any pertinent information
	* Rule of thumb: Show what you will export and no more.
	* Currently the external wall and perimeter depth walls provide sufficient data for downstream apps.
[x] 2017-09-21 ~ Finish add data reporting parameters, eg openings, adjacent buildings
* 2017-09-22 ~ Consider more suitable name for this menu item
* 2017-09-22 ~ Add ground that can receive shadow
* Add quite a bit of text to read me

**Comment by bwelle** [comment]
Hi Theo, the link doesn't seem to work for me. Broken.

**Comment by theo-armour** [comment]
http://www.ladybug.tools/spider/sandbox/build-well/r7/index.html

**Comment by bwelle** [comment]
Great. Reviewing now. Shall I put bug list here? Where would you like me to post remaining dev items that are critical path for GUI?

**Comment by theo-armour** [comment]
@bwelle 

My bad. I simplified the naming system, but it looks like I did not save changes to one critical file in the process.

In principle you should always be able to go here and get the latest file:

http://www.ladybug.tools/spider/sandbox/build-well/

Last night, the index.html file that takes care of this process was not properly updated. ;-(

It takes a while for things to propagate and caches to be cleared, but I think it's working now

**Comment by bwelle** [comment]
Bugs:
AdjacentBuilding
1. If I change Anton Building to -170 y offset, building moves and grid doesn't update.
2. If I play around with numbers, the grid does update, but then when move building back to original setting, the grid doesn't reduce in size again, it stays big.
3. When I change height to 90, no update. I need to click to another input and change it, like orientation, until height updates.

Box: 
1. If update Building Area to 10000, nothing happens, until click on Length field and change it. We discussed increasing/decreasing the default length auto by the ratio change in Building Area automatically, and thus the width updating to maintain same building aspect ratio.
2. When click back on Adjacent Building tab, then back to Box tab everything resets still. Would like to keep last values as the user will toggle back and forth between the two tabs.
3. Please put ground toggle to off as default and edge toggle to true as default.

**Comment by theo-armour** [comment]
Folloing will be includd in latest update some time today:

> If I change Anton Building to -170 y offset, building moves and grid doesn't update.

I think I've fixed this. Still checking:

> If I play around with numbers, the grid does update, but then when move building back to original setting, the grid doesn't reduce in size again, it stays big.

Interesting. Checking for bigger is easy: you only need to check whether the most recently moved object has gone out of the grid. Checking for small means you have to loop through all the buildings and all their XY coordinates. Very doable. Might slow things down. But main thing is that it will take several hours of coding to build and test. Can we put 'smallerize the grid' on the 'to do' list for time being? If needed badly. I could add a 'check if smaller and fix if it is' button. but even that will take thought.

> When I change height to 90, no update

Ooops, a typo got in there

**Comment by bwelle** [comment]
Yes, smaller grid leave for later

**Comment by theo-armour** [comment]
> Please put ground toggle to off as default and edge toggle to true as default.

Ground is now off as a default

Edges are on as a default. But disappear as soon as a building is edited. 

There is a much larger discussion to be had regarding the colors and materials of elements, shade and shadow. and more. It seems to me the best time for that discussion - and do these sorts of updates - will be after the shape creation and editing process is cool and we are successfully exporting data to gbXML and NREL JSON.

**Comment by bwelle** [comment]
Agreed. After gbXML. Before NREL as we don't need that.

**Comment by theo-armour** [comment]
> When click back on Adjacent Building tab, then back to Box tab everything resets still. 

Yup, first step was going from box to adjacent without loss of memory. Now we have to remember how to get back to box or ell.

**Comment by theo-armour** [comment]
## [Build Well R 7.1]( http://www.ladybug.tools/spider/sandbox/build-well/r7/index.html )


## Change Log

* R7.1
* Numerous minor updates following bwelle suggestions
* Adds gbXML Export menu 'prequel'

**Comment by bwelle** [comment]
Floor area is incorrect. When change 4000 total area to 2 floors, it shows single floor as 1000 rather than 2000.

**Comment by bwelle** [comment]
Is there a way to always have edges?

**Comment by bwelle** [comment]
Add opacity slider.
