### ISSUE TITLE
Update 2017-09-29 ~ gbXML Viewer 'Mostapha' Release 

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#24]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/31041729-32019b44-a54f-11e7-8b83-315185b56583.png)

## Change Log

Preliminary release. Only handles a single model.

Next release should have usual features plus: actual holes in the surfaces and not just black blobs. After that will come colors and shading

* gbXML Viewer 'Mostapha'
* Another big jump: now depicting Surfaces and Openings
* Code quite a bit smaller and tighter

**Comment by mdengusiak** [comment]
Good to see windows :)
