### ISSUE TITLE
Build Well L-Shape Updates

### ISSUE THREAD

**Issue by bwelle** [ladybug-tools/spider#25]
Let's use this issue for L-Shape specific issues.

**Comment by theo-armour** [comment]
@bwelle @antonszilasi 

I am looking at: L-Shape Equations.pdf (sent privately) - more specifically at 'Parametric Relationship =
L-Shape-1'

If you change the total area of the building, how does that affect the length (X1) of the building?

**Comment by bwelle** [comment]
L-shape equations need not be private, you may post. I believe for L shape same method applies when changing Total area and # of Floors as does for box. Take fraction increases/decrease, take sqrt, and multiply by all dimensions (or in this case apply to independent value X1 and the rest should update accordingly).

**Comment by bwelle** [comment]
From previous email...

a.	Current Bugs:
   i.	Going from Adjacent Building to Box tabs without losing data.
   ii.	Floor Area not updating correctly with new “proportional dimensions” update.

b.	To-Do List:
   i.	Put x,y,z axis on the ground plan, make it black and thicker and larger so it's very clear to the user visually, and put letters x,y,z on them. 3D text.
   ii.	Add new window inputs and logic to place window arrays. Link to Git code posted. Need to add two more inputs to Box tab: # of Windows and a slider for Window Proportions. Theo, I sent you what I have, let me know if you need more.
   iii.	Add N,S,E,W letters to 3D view. Calculate based on angles so updates as rotate building. Make letters 3D.
   iv.	Change “Building Length” to “Length 1 (X1)”. Change “Width 1 (Y1)”. This will help the user understand the dimension better, and associate it with grid dimensions and the equations we show on the 2D view. 
   v.	Create 2D view somewhere that updates with 3D. Orthographic view like you said. Show equations in 2D text along building sides. When first show box, show equations on each side (Length 1 for x side and Width 1= (Building Area)/Length 1 for y side). Theo, we may choose to show equations in terms of x and y, but we can change this ourselves once we see how text laid out.) Once user starts entering new values for independent parameter (Length 1) or changing parameters that change dimensions such as # of Floors, Building Area (maybe orientation too so you don’t have to rotate equations?), we want to start showing actual numerical values for the sides in the 2D view rather than equations. 
   vi.	Add Opacity slider.
   vii.	Have “edges” enabled at all times.
   viii.	How account for the user changing units from IP to SI? Implications for code? Assume the user selects IP or SI at the beginning of the project and it doesn’t change (i.e. they don’t change units mid geometry entry).

**Comment by bwelle** [comment]
3.	L-Shape: Fortunately, with the Box logic complete, there are only a few things to enable a new shape such as this L.

a.	Match all the functionality for the Box-Shape.

b.	To-Do List:
i.	Add an input called “Parametric Relationship”. Give the dropdown 2 values: “None” and “L-Shape-1”. Make this the first input. Default to “L-Shape-1”.
ii.	If “None” selected, the following input dimensions appear: Length 1 (X1), Width 1 (Y1), Length 2 (X2), Width 2 (Y2). Length 1, Width 1, Length 1 are independent (unlocked), only Width 2 is locked. 
iii.	If “L-Shape-1” selected, the following input dimensions appear: Length 1 (X1), Width 1 (Y1), Length 2 (X2), Width 2 (Y2). Length 1 is unlocked, Width 1, Length 1, and Width 2 are locked. 
iv.	Equations to show on original 2D view and to calculate all the dimension values are shown in the [attached pdf](https://perkinswill.box.com/s/2oduw6q4gw1injobs3qhh0kec8owxroa).
v.	Use the following default starting values:
a.	L-Shape-1: Building Area: 4800 ft2, Length 1=80ft, # of Floors=1, Floor Height=12, Perimeter Depth=10, WWR=40, Overhang Depth=0, Orientation=0. Other dimensions calculated.
b.	None: Building Area: 4800 ft2, Length 1=80ft, , Width 1=80, Length 1=40. # of Floors=1, Floor Height=12, Perimeter Depth=10, WWR=40, Overhang Depth=0, Orientation=0. Other dimensions calculated.

**Comment by bwelle** [comment]
My thinking is user lands on the above geometry for L-Shape-1. If they change Building Area or # of Floors, we update automatically the dimensions per the Box strategy. The user may still go to the independent parameter and modify within a limited range...for now it is assumed they will visually make sure the new value works. We will add automated checks later.
