### ISSUE TITLE
Build Well 3D Scatter Plot

### ISSUE THREAD

**Issue by bwelle** [ladybug-tools/spider#28]
Here is where we will discuss the 3D scatter plot. I assume we will have a separate Build issue for this.

**Comment by theo-armour** [comment]
@bwelle 

**Naming considerations**
I see 'build well' as part of a bigger spider web wellness thing.

So there could be a 'room well' or 'space well' project for the room builder project for Mostapha.

That makes me thing this project could be the 'Scatter Well' or 'Scatter Plot Well' project: useful for any sort of 3D plotting.

I will be adding a separate folder in the sand box - when we have the name for it.

Just thinking out loud.

**Comment by theo-armour** [comment]
@bwelle 

Can you provide a rough estimate of 

* how many data points will be involved
* how many variables might be attached to each data point?

**Comment by theo-armour** [comment]
@bwelle @antonszilasi 
 
sketching or thinking out loud

## http://www.ladybug.tools/spider/sandbox/scatter-well/

![image](https://user-images.githubusercontent.com/547626/31155659-9897a7e6-a864-11e7-9823-729fc92ad79b.png)

**Comment by bwelle** [comment]
love it. Even has the ability to click on point and view data and an image. That's what we want at a minimum (zooming in and seeing actual building geometry is wish list).

**Comment by bwelle** [comment]
Once we get the csv generated and posted, I'll provide detailed specs.

**Comment by bwelle** [comment]
This comment also in R1 spreadsheet issues, but thought it might be more appropriate here...

@theo-armour,

Ok, ready with some details on this 3D Scatter Plot. This will the funnest viz to do, the most compelling to the research advisory board, Phil our CEO, and almost every architect. This is the money visualization. 3D Scatter Well. I'm proposing to something no one has ever done in the AEC industry as far as I know.
I’ve updated the google sheet Anton sent. Input values in red are the dynamic inputs (ones that change) to be displayed in pop-up window when hover over design, and in the left hand panel to select for the graph, and as design constraints with duel slider. The blue ones are the outputs that may be shown in the pop-up window, left hand panel to select for the graph, and as performance constraints. The uncolored input values need not be displayed, and are only included so as to make available to you all the inputs needed to regenerate the geometry rather a single point in the scatter plot. At the end of each row in the google sheet is the name of the according SVG image.

On the interface, you will want to list all the inputs vertically in a list with a checkbox next to it, then a dropdown menu called Axis where you can select x,y, or z next to each checkbox. Put all these inputs under the heading "Design Parameters". See slide 3 here…

Then you will want to create a heading "Building Performance". List the outputs, again with a checkbox next to each one and a drop down menu for axis. The user must select one input and two outputs via the checkbox, then assign which of the three axis they want to view the three parameters. See slide 3 above as well.

Now for the actual Scatter Plot. In addition to each point displayed on the chart based on the user checked input and outputs (3 total) and axis, there needs to be a slider under the heading Design Constraints for each input variable. Then under the heading Performance constraints, there needs to a slider for each output. This is where the user can specify lower and upper limits for each input and output to eliminate points from the scatter plot and reduce the size of the point cloud. Rather than making the points disappear that fall outside the constraints, it would be preferable to grey them out to a very light semi-transparent grey. See slide 4 above.

Each slider has the range for the given parameter that exists in the CSV file. Numerical sliders may be true sliders (meaning if range of values is 3,4,5, you can put 3-5 as range, and 0-30 for orientation, even though there are only two valid values, 0 and 30), while discrete inputs such as Window Construction will have several points to jump to. Maybe we want to make numerical value sliders actually be enumerations of valid values. Not sure how best to show construction names in the slider. Output slider constraints may simply be a true slider with all values possible between the ranges (since there are many possible outputs, as opposed to only a limited set of valid inputs0. Each slider has two little control points so they can specify a minimum and maximum. All the above applies to outputs.

Finally, you need to put a slider under the heading "Output Preference". The slider goes from 0-100, and defaults to 50. The two outputs selected appear at either end of the slider, with a toggle switch to minimize or maximize that parameters. Then as you move the slider off of 50 (which is equal preference), closer to one of the objective parameters, the colors of the design points change accordingly (in the 2D axis with both outputs, colors don't change across the input. Somewhere the ranges for colors and output preference values is in the code for most preference shading modules. I'm sure three.js has somthing.

So that takes care of coloring convention for the points, and determine which points are greyed out due to being outside a design or performance constraint. See slide 4 above.

Next, we will want the user to hover a given point in the scatter plot, and have design summary window pop that lists the other input and output values, and has an svg image of the actual geometry below it. The SVG reference for each point is at the end of the CSV.

Inputs (Ignoring units):

Footprint Shape
Width 1 Y1
Num of Floors
Floor Height
Orientation
WWR_S
Overhang Depth S
Window Construction
LPD
Outputs (ignoring units)

Annual Cooling Load
Annual Heating Load
Total Solar Load
EUI
Inputs Ranges:

Footprint Shape – (L,T,H)
Width 1 Y1 – (80,100)
Num of Floors – (1,2)
Floor Height – (3,4.5)
Orientation – (0,30)
WWR_S – (0.4,0.8)
Overhang Depth S (0.6,0.9)
Window Construction (ASHRAE 189.1-2009 EXTWINDOW CLIMATEZONE 3, CBECS 1980-2004 EXTWINDOW CLIMATEZONE 4A, ASHRAE 90.1-2010 EXTWINDOW NONMETAL CLIMATEZONE 7-8)
LPD (7,12)
Outputs Ranges
5.	Annual Cooling Load - (93195-273677)
6.	Annual Heating Load – (317908-725639)
7.	Total Solar Load - (218978-1262900)
8.	EUI – (116-264)

One final thing. We'd like to show the Pareto Front in 3D, meaning the points where you cannot improve in one objective without worsening in the other. These points should be designated with bold X's. To calculate these points, I found the following JS libraries here and here:

I'd be totally stoked to get to this point. I still have that image in my head of when you zoom in have the points actually show the building geometry of that design (that's why i included the footprint dimensions in the inputs CSV), so if we have time for that, I know that would blow architects away. They've never seen that.

**Comment by theo-armour** [comment]
@bwelle

**Generally**
We very much need to discuss what I do and what Anton and ME do. In your spec there are a lot of user experience/user interface that do not need/should not have my level of craziness. My work should be taken as demos built by an artist that real programmers should take as as inspiration and guidance while taking much of the entry level code I produce with a grain of salt.
 
**> I still have that image in my head of when you zoom in have the points actually show the building geometry of that design**

I do too. And frankly I think the shapes can be in there from the get-go. After all, the number of faces in H, L or T shapes is a lot less than the faces in the average sphere. I have started with simple shapes and scaled them roughly. In any case each data point can have its own symbol that represents the shape in question, scale height, length and width along with orientation. Cooling and Heating loads can be X and Y. Solar load can be Z and EUI can be color. And actually you should be able to switch around all four variables to any axis or color of your choice- if you wish.

But if that does not work then we could drop back and have the shape created in the HUD. Or try switch spheres for shapes. I do like the idea of all shapes from the get go. And I hope you will help explore this path.

****

Remember that the graph is linked to the spreadsheet in real-time - so always check the graph to make sure there are no issues. I will be boosting back up the size of the symbols soon.

Looking forward to the new data

**Comment by bwelle** [comment]
@theo-armour 

We very much need to discuss what I do and what Anton and ME do. In your spec there are a lot of user experience/user interface that do not need/should not have my level of craziness.
