### ISSUE TITLE
Update 2017-09-30 ~ gbXML Viewer 'mostapha].1 ~ very holey release

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#32]
@ladybug-tools/spiders 
![image](https://user-images.githubusercontent.com/547626/31051646-3509fd30-a622-11e7-9cf4-78d1d3572ee8.png)

## Change Log

We have holes!

We display multiple files. 

Coming next: Load files from disk. Colors, shade and shadows

* gbXML Viewer 'Mostapha'.1
* Displays surfaces with openings reasonably well.
* Speed is OK

**Comment by theo-armour** [comment]
@ladybug-tools/spiders 

mostapha.1

![image](https://user-images.githubusercontent.com/547626/31065663-fd95428a-a6fb-11e7-960a-feb34bf5f176.png)

* Opens and displays local files using your file dialog box

**Comment by theo-armour** [comment]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/31065732-8d5eb3f6-a6fc-11e7-9559-6c4930276d4c.png)

mostapha.2

This is the first pass at adding colors(random), lights, shade and shadow.

**Comment by mdengusiak** [comment]
I like this carpet style on floor,
so far seems that shade are more correct outside than not inside

![image](https://user-images.githubusercontent.com/14005893/31198082-faf5299a-a94a-11e7-8c36-3f82f9cac7a2.png)

**Comment by mdengusiak** [comment]
I tested second file and not sure a bit of roof is missing.
It is good to see how everything is developing so fast... :)
![2017-10-04 21_37_32](https://user-images.githubusercontent.com/14005893/31198729-2a7daef6-a94d-11e7-86bf-491ab9110af2.gif)

**Comment by theo-armour** [comment]
@mdengusiak 

Thank you for the feedback, 

The 'carpet' has something to do with shade and shadows. Three.js has a number of shading and rendering settings. And these will need tweaking.

The current priority is creating files that Open Studio is amble to import. Once that process is well-established then we can tackle the appearance issues in detail. For the moment, I am only tweaking things like materials only as much as needed to help verify geometry.

As I write this, I am enjoying your animated GIF. Was your view of the model created using the KIT.edu Viewer?

**Comment by mdengusiak** [comment]
This is created using opensource:

https://www.gimp.org/downloads/

here is tutorials...sometimes you need to go to Layers and reverse order...before you export..
![2017-10-06 17_07_27](https://user-images.githubusercontent.com/14005893/31287721-2ad6d38c-aaba-11e7-8e6d-379d270027cf.gif)
