### ISSUE TITLE
Update ~ 2017-10-05 ~ gbXML Viwer mostapha.4

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#36]
@ladybug-tools/build-well @mdengusiak 

![image](https://user-images.githubusercontent.com/547626/31257499-b045da68-a9ed-11e7-8367-3b6522640ceb.png)

## Full Screen: [gbXML Viewer]( http://ladybug-tools.github.io/spider/read-gbxml/gbxml-viewer/index.html )

This interim update is just to help with validating/verifying gbXML export files created by current release of Build Well

## Change Log
* gbXML Viewer 'Mostapha'.4
* Very messy, broken release with one nice new feature
* Adds: heads-up display(HUD) that shows details/data of the surace currently under the corsor
* Displays more (not all) meta data in side menu

**Comment by theo-armour** [comment]
See also #35

**Comment by mdengusiak** [comment]
This looks good, but would be amazing to see also names, CADObjectID so we can relate which space it is and easily find in Revit.

![2017-10-06 16_44_07](https://user-images.githubusercontent.com/14005893/31297448-ed45ac4a-aadd-11e7-887f-d697e9bd1936.png)

![image](https://user-images.githubusercontent.com/14005893/31297646-c42bec2e-aade-11e7-800a-41bf776cebad.png)

**Comment by theo-armour** [comment]
Adding building story and spaces to Build Well gbXML Export what I am
working on right now. Once I have learned how to create these things then
learning how to read them in gBXML Viewer should be easy.

**Comment by theo-armour** [comment]
Something like the following?

![image](https://user-images.githubusercontent.com/547626/31303599-31db478e-aac5-11e7-9642-51bad9e4a0ce.png)


## http://www.ladybug.tools/spider/read-gbxml/gbxml-viewer/2017-09-29-mostapha/gbxml-viewer.html
