### ISSUE TITLE
Update 2017-10-10 ~ gbXML Viewer R5

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#39]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/31406677-17eab96e-adb7-11e7-9c4c-3535c051acaf.png)
_Open Studio sample OSM file exported as gbXML and displayed in Ladybug-Tools/Spider/gbXML Viewer R5_

## Full Screen: [gbXML Viewer R5]( http://ladybug-tools.github.io/spider/read-gbxml/gbxml-viewer/index.html )

Core code is beginning to settle down. Need URL access to many more gbXML files for testing.

After a bit more code clean up and modularization, it might be time to start thinking about new features. 

## Change Log

* gbXML R5 ~ back to a regular numbering system
* Improve object higlighting
* Improve lighting and shading
* Improve camera & controls distance control
* Add opacity to buildings
* Add select materials
* And quite a few other fixes

**Comment by mdengusiak** [comment]
Hi

I tried this version today and can not see anything? 
Why?... is code is a state that does not display model currently?

![image](https://user-images.githubusercontent.com/14005893/31407844-aefec53a-ae06-11e7-9917-8153f94356a4.png)

**Comment by theo-armour** [comment]
@mdengusiak 

I'm checking

Working for me on: 
* Win10 / Chrome
* Chromebook/Chrome
* Win10/FF

Having issues on
* Google Pixel XL/Android/Chrome

Have you tried a 'hard reload'? Control-Shift-R. Often there are chaching issues...

**Comment by theo-armour** [comment]
@mdengusiak 

Is the JavaScript Console displaying an error message?

**Comment by mdengusiak** [comment]
It made a trick...
it looks ABSOLUTELY AMAZING!
easy to navigate, fast

![image](https://user-images.githubusercontent.com/14005893/31410212-68d8ed4e-ae0e-11e7-8b20-cc4a12f99cb0.png)

ps. only floors seems to have not correct data, should be not raised floor

**Comment by theo-armour** [comment]
> ps. only floors seems to have not correct data, should be not raised floor

I will double check. I started adding more HUD items at the last minute.

**Comment by mdengusiak** [comment]
Is this are sun vectors? what is plan to visualize this at the end
![image](https://user-images.githubusercontent.com/14005893/31465214-2df8aa62-aecb-11e7-809d-f87dea0c0048.png)

I love fact that I can copy Revit Element ID and then paste in Revit to find it there
![2017-10-11 21_30_20](https://user-images.githubusercontent.com/14005893/31465341-a09a787a-aecb-11e7-871d-879050ed6596.png)

I can select side surfaces and selection is pink:
![image](https://user-images.githubusercontent.com/14005893/31465956-6f463992-aecd-11e7-8b93-503847283be3.png)

but when I do front selection it does not highlight the same way:
![image](https://user-images.githubusercontent.com/14005893/31465988-8d1bafec-aecd-11e7-9b42-a7deb1870883.png)

ps. can we add units to area.. m²   and maybe round to 3 decimals.. I think 1 mm precision is enough

**Comment by mdengusiak** [comment]
ps. I tested extreme stress test with my tower 336MB but it was too much

![2017-10-11 21_55_26](https://user-images.githubusercontent.com/14005893/31466434-0c0397e2-aecf-11e7-80c1-dbb4f9095634.png)

![image](https://user-images.githubusercontent.com/14005893/31466424-04ab5d72-aecf-11e7-9c3b-1d7ae5e45bcc.png)

**Comment by theo-armour** [comment]
@mdengusiak 

Thank you for your support and hands-on feedback. I can't express how much this motivates my efforts.

> Is this are sun vectors? what is plan to visualize this at the end

Currently the Light is being positioned at XYZ = 1.5 * radius, 1.5 * radius, 1.5 * radius where radius is the bounding sphere of the geometry. Very boring.

Plan is to do better than this:

![hong-kong-epw-json-3d-2-iloveimg-compressed](https://user-images.githubusercontent.com/547626/29483608-ec0bbed2-845e-11e7-9f07-99fc293705a6.gif)

See https://github.com/ibpsa2017/ibpsa2017.github.io/issues/6 for more details.

> I can select side surfaces and selection is pink:
> but when I do front selection it does not highlight the same way:

I think a lot of this has to do with the normals of the surfaces. My feeling is that there are no easy fixes here and it will take a while to cover all the possibilities. But you never know. Sometimes good answers pop up like magic.

>ps. I tested extreme stress test with my tower 336MB but it was too much

Cool! Can you describe what your stress test involved

**Comment by mdengusiak** [comment]
OK future looks bright,

I tested to import my biggest building in gbXML with over 5000 spaces - two towers on common podium which is 336MB. I think too much for chrome right now.

**Comment by theo-armour** [comment]
> I tested to import my biggest building in gbXML with over 5000 spaces - two towers on common podium which is 336MB. I

Yes, I find that there's a limit around 100MB with JavaScript. But there are a lot of tricks, The JavaScript htmlrequest thing allows you to load parts of a file by allowing you to specify the start and stop bytes. So if you know something about the file or the project you can code around the limitations. Alternatively we could think of translating from gbXML into JSON or even a CSV file.

Is the 336MB file - or something like it -  available on line anywhere?

> Three.js menu

We can add anything, anywhere. ;-)

Your wishlist is my command line.
