### ISSUE TITLE
gbXML color palettes /schemes for surface types 

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#42]
according the [gbXML-Schema]( https://github.com/GreenBuildingXML/gbXML-Schema ), gbXML has the following types of surfaces:

* InteriorWall
* ExteriorWall
* Roof
* InteriorFloor
* ExposedFloor
* Shade
* UndergroundWall
* UndergroundSlab
* Ceiling
* Air
* UndergroundCeiling
* RaisedFloor
* SlabOnGrade
* FreestandingColumn
* EmbeddedColumn

Future releases of gbXML Viewer and Build Well will enable the ability to display each of these surface types with its own colors, textures or shaders. Right from the beginning it would be nice to have a variety of color palettes or schemes available.

I note that @mdengusiak kindly posted a list of colors for many but not all here: https://github.com/ladybug-tools/spider/issues/16

1. Does anybody have or know the location of any standard (or non-standard) gbXML color schemes that covers all surface types?
2. Are there any surface types not in the Schema that we should be covering?

**Comment by mdengusiak** [comment]
Hi,
there is not any color standard, I will update my list to include all elements. 
Revit does not support many from this list yet and I believe if we get all this included this would be great. And should cover most of the cases. 

There is one type of spaces in gbXML that not sure are included - external spaces. We have some open space that is on the top of roof - play court. We can tick that is external space but we can add some load ie. lighting.

**Comment by theo-armour** [comment]
@mdengusiak 

> I will update my list to include all elements

Great!

Numbers are good for identifying colors. And words are even nicer!

W3schools has a nice page list all the web standard color names here

https://www.w3schools.com/colors/colors_names.asp

It would be nice to have one or more color schemes based on these names.

In terms of coding, hex numbers - #ff0000 for red - are easier to work with than RGB colors ( 255, 0, 0 )

In any case, we will end up, I hope, by supporting all three and more (HSL etc).

> There is one type of spaces in gbXML that not sure are included - external spaces. 

Good suggestion.

I will add external spaces to the list

**Comment by mdengusiak** [comment]
@theo-armour 
OK to help you I will add this in format. With RGB, HEX we have full freedom.
so you need sth like that below?

- SurfaceType, Color RGB, Color Hex
- InteriorWall, rgb(0, 128, 0), #008000

**Comment by theo-armour** [comment]
@mdengusiak 
Bingo!

**Comment by bwelle** [comment]
@theo-armour @mdengusiak 

I personally don't have a preference for color shading at this point, but I fairly consistently see light beige to more yellowish for shading objects such as adjacent buildings and overhangs/fins. I do like that, as it it easy to distinguish from most other colors typically used for surfaces.

**Comment by mdengusiak** [comment]
@theo-armour 
As promised here is updated list,
**SurfaceType	| Color Hex**
InteriorWall	#008000
ExteriorWall	#FFB400
Roof	#800000
InteriorFloor	#80FFFF
ExposedFloor	#40B4FF
Shade	#FFCE9D
UndergroundWall	#A55200
UndergroundSlab	#804000
Ceiling	#FF8080
Air	#FFFF00
UndergroundCeiling	#408080
RaisedFloor	#4B417D
SlabOnGrade	#804000
FreestandingColumn	#808080
EmbeddedColumn	#80806E
![image](https://user-images.githubusercontent.com/14005893/31637567-2ab03456-b2c7-11e7-8293-29285f8341ea.png)

**Comment by theo-armour** [comment]
@mdengusiak 

Thank you for your color scheme. I look forward to seeing the colors in action.

I hope we will have multiple schemes you can choose from.

Can anybody find what the Grasshopper/Honeybee gbXML readers has as a color scheme? I looked through the source code but code not find it.

Also how about somebody making a list based purely on color names from here: https://www.w3schools.com/colors/colors_names.asp ?

such as:

InteriorWall: azure</div>
ExteriorWall: cornsilk
Roof: crimson
and so on...

**Comment by michalinadengusiak** [comment]
@theo-armour  here is my idea for the building color scheme

InteriorWall = LightSlateGray
ExteriorWall = Plum
Roof = DarkSeaGreen
InteriorFloor = HotPink
ExposedFloor = DarkOrchid
Shade = DarkGray
UndergroundWall =Indigo
UndergroundSlab = Navy
Ceiling = LightPink
Air = AntiqueWhite
UndergroundCeiling = RosyBrown
RaisedFloor = Pink
SlabOnGrade = DarkViolet
FreestandingColumn = GoldenRod 
EmbeddedColumn = Gold 

Michalina

**Comment by theo-armour** [comment]
Thanks @michalinadengusiak 

I will include this color scheme in the next release.

Can you supply a name or title for this color set?  I hope - eventually - there will be a number of color sets - suitable for different regions and different building types. We will keep you busy.

Anyway, we will need good, fun names for each scheme - maybe something like: 'oslo-hospital', 'riyadh-office' or 'hong-kong-farm'?

**Comment by michalinadengusiak** [comment]
Thanks @theo-armour 
I think `Tokio-mini-office`

Michalina

**Comment by theo-armour** [comment]
@michalinadengusiak 

Warwick University building with tokio-mini-office colors

![image](https://user-images.githubusercontent.com/547626/37575309-c3480f42-2ae3-11e8-8e12-6574f0fa85d2.png)

Bristol / Clifton Down Road with tokio-mini-office colors

![image](https://user-images.githubusercontent.com/547626/37575410-3bfdf104-2ae4-11e8-9b4f-7e8d88f92a65.png)

Download tokio-mini-office file from here: https://github.com/ladybug-tools/spider/tree/master/gbxml-sample-files/save-changes-samples and save to loacal hard disk,

In gbXML Viewer use the, 'manage save changes files' button open menu, then choose the file you just saved.

You could make more color schemes by changing the color names and saving to a new file. I will work something out so we can update building colors by clicking on a menu.

Thank you again. Very nice colors!

**Comment by michalinadengusiak** [comment]
@theo-armour 
I tried on 11.12.6 but it didn't work
![image](https://user-images.githubusercontent.com/37042279/37675956-e792cb0a-2c76-11e8-8eb1-8be28f0acdd1.png)
it also didn't work on 12.5
![image](https://user-images.githubusercontent.com/37042279/37676082-3a73c572-2c77-11e8-875d-fb7e17f3086e.png)

**Comment by michalinadengusiak** [comment]
@theo-armour 
Sorry it worked

**Comment by theo-armour** [comment]
@michalinadengusiak 

The code for changing colors only started in R12.3. Earlier release have no color changing capabilities

in 12.5, the default colors are 'tokio-mini-office colors' so no changes needed to be made in order to see these colors. (Also the text report in color changing is not yet finished. There could be a message that colors have not changed. )

![image](https://user-images.githubusercontent.com/547626/37676575-8787a29e-2c35-11e8-9fb6-75b39515f830.png)

**Comment by michalinadengusiak** [comment]
@theo-armour 
Please find the colour scheme for different orientations.
North : Blue
North East : Magenta 
East: DarkOrange 
South East : OrangeRed 
South items: Red
South West items: Salmon
West Chocolate 
North West : Gold
Michalina

**Comment by mdengusiak** [comment]
@theo-armour  @michalinadengusiak 
a new color scheme looks great I will close this issue as we have amazing color scheme in R12.14
