### ISSUE TITLE
gbXML metric defaults

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#43]
With the new menu system in Build Well and gbXML Reader, it is going to be much easier to build menus for different measurement standards and different languages.

In order to build the first set of demo menus, we need defaults, minimums and maximums for

* Perimeter depth
* Overhangs
* Floor height

@bwelle has supplied US defaults and these are what is currently available.

What should the metric defaults be? 

And should we have separate demo menus for cm and mm standards?

**Comment by mdengusiak** [comment]
@theo-armour 
1. I think for buildings scale we should use [m] meters this should be sufficient, please allow decimals so we can type 65.508 [m] in this case we cover also [mm] case if anyone needs this.

2.Not sure why I can not type decimals in current version 10.2 because of units?
![image](https://user-images.githubusercontent.com/14005893/31588707-20ec6862-b1f6-11e7-857b-ae70b881a894.png)

3.Please implement Units conversion to [m] so I can see current default settings.

**Comment by theo-armour** [comment]
@mdengusiak 

This menu is set up for integer feet - to keep things very very simple for us Americans.

The metric demo menu will of course be full floating point.

We might be able to play with the up down arrows so values jump by 10mm or 100mm, but let look at those enhancements once a menu is first built.

**Comment by bwelle** [comment]
@theo-armour @mdengusiak 

So as I understand it, we are going from unitless inputs to menus for tabs or conversion field from IP to SI. That's fine for me, as you need to know units for the gbXML export. As Theo mentioned, most of our users, especially in early phases of deployment, will be using IP. However, we have many non-US offices using SI (and in fact, the convention we decided upon with our web GUI is not matter what the entry units are, we export to metric for use in OS API and everything downstream. How we handle it in the GUI is we use defaults and enumerations listed in a JSON file for various fields in IP. Then if the user toggles to SI, we use simple conversion equations to change value to SI. Here are the equations, which are official conversion used in Open Studio:

1 ft^2 = 0.092903 m^2
1 m^2 = 10.7639 ft^2
1 ft = 0.3048m
1 m= 3.281 ft

So for Build Well, I would proposed I provide defaults/enumerations in IP, then when in SI mode use those conversion factors.

I don't foresee any need for mm or cm. I rarely see anyone wanting to use this.

**Comment by bwelle** [comment]
>In order to build the first set of demo menus, we need defaults, minimums and maximums for

Perimeter depth
Overhangs
Floor height

I will provide a revised set of IP defaults to you @theo-armour given that now we are addressing the issue of conflicting dimensional parameters. More on this to come.

**Comment by bwelle** [comment]
@theo-armour 
I see only 10.1 posted. Mike mentioned 10.2. Is that link somewhere else?

**Comment by mdengusiak** [comment]
I think I mess sth up...I guess I saw 10.2 but it must be 10.1..
I agree we use deafults from your IP * conversion as start and then we see if we need some separate defaults inputs in case sth looks silly... but lets start per @bwelle  suggestion
