### ISSUE TITLE
gbXML perimeter depth issue proposal

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#44]
@ladybug-tools/build-well 

In the current Build Well, if the length or  width of a space is less than twice the perimeter depth then the interior wall is not created. For example, in the Box shape, reduce the length a lot to make a long very skinny building and watch all the interior walls disappear.

This was fine for getting started, but managing the gbXML zones and spaces if walls come and go, becomes much more complicated.  And this probably makes the downstream calculations using zones and spaces even more complicated. This code can and should be written. but in this first generation of Build Well it may be better just to have a few simple rules.

I propose that:

All shapes have a minimum dimension of a little more than twice the minimum perimeter depth.

This means that all shapes all always have their normal set of zones and spaces. And there is always and interior zone - even if it's quite tiny.

If you choose a dimension of a space that is smaller than twice the current perimeter depth then the code asks you to reduce the current perimeter depth and try again.

Unless I hear a better suggestion, I will start to code something like this in an upcoming release.

**Comment by bwelle** [comment]
@theo-armour 
Glad we are on this topic. This is an issue for our GUI as well. I have a proposal of how to address it, will review the one above, and get back to you in a few hours of a synthesized proposal of how to handle.
