### ISSUE TITLE
Update 2017-10-20 ~ Build Well R12 ~ spaces have individuated floors

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#47]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/31846118-376a0314-b5bc-11e7-9b6a-9957fc33a12d.png)

## Full Screen dev release: [Build Well R12]( http://ladybug-tools.github.io/spider/build-well/dev/index.html )

Save these links

* Build: <http://www.ladybug.tools/spider/build-well> << always the current (safe?) release 
* Dev: <http://www.ladybug.tools/spider/build-well/dev > << the work-in-progress (may be broken) release
_fingers crossed one of them work for you_

Note: gbXML export is a release of two behind the current geometry

## Change Log

* mnu-template.html
	* Clicking on info icon takes you to source code
* build-well.html 
	* Clicking on info icon takes you to source code
* mnu-box-shape.html
	* looking good: 2017-10-14 ~ add individuated floors and ceilings
	* id/zones numbers start from south side, run clockwise: 2017-10-14 ~ Revisit space id naming
* mnu-ell-shape-one.html
	* Clicking on info icon takes you to source code
	* correct issues with wall placements
	* looking good:  2017-10-14 ~ add individuated floors and ceilings
	* id/zones numbers start from south side, run clockwise:  2017-10-14 ~ Revisit space id naming
* mnu-hud.html
	* Mostly working as intended
	* working: 2017-10-14 ~ Highlight The Building when selected
* R12 started

**Comment by bwelle** [comment]
@theo-armour 
Tested export and import into OS desktop. Nothing comes in but overhangs. Error says: Surface has no adjacent spaces, will not be translated. Missing some adjacent space IDs.

Surface has no adjacent spaces, will not be translated.

Let me look a little deeper...I see some other things, hold on...

**Comment by bwelle** [comment]
@theo-armour 

Import breaks in OS. Says surfaces missing adjacent space IDS. 

The naming convention is perfect!

I see on issue right away...the perimeter roof surfaces you call "ceiling". It should be roof. Ceiling is reserved for interior surfaces.
