### ISSUE TITLE
Update 2017-10-22 ~ Build Well qLine ~ Saturday night coding

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#49]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/31859601-01b6d618-b6c3-11e7-8d1a-390758c2179d.png)

## Concept

This side project is an alternative to: http://rawgit.com/ladybug-tools/spider/master/build-well/r11/build-well.html

The code here is based on the idea of extruding a shape and making that shape follow a given path.

The code handles any shapes squares,, rectangles, stars, irregular polygons and so on. Whatever comes out of a pasta machine etc could be replicated here.

The path of extrusion - currently 2D only - may be made up of straights and curves. Pretty much whatever you can create as a line in SVG can be used as the path of the Qline.

Another thought is that there is no intention to create anything that looks 'realistic'. The idea here is to generate schematics quickly and easily. In order to speed the process a number of shapes can be displayed simultaneously. 

One you are happy with a selection, adjacent buildings could be added and the ensemble exported as a gbXML file. When projects need to be shown to clients, then the files may b open and displayed using gbXML viewer.

And, as always, it's nice to have to see things in a fun, colorful game-like fashion.

## Naming considerations

AutoCAD has a marvelous 2D drawing command titled 'polyline' - often called 'pline'

If one were to invent a new drawing command - designed to be what comes after the pline, then maybe it could be called a 'qline'. As in what comes after the letter P?

 ;-)

### 2017-10-21 ~ Theo

* First commit

**Comment by theo-armour** [comment]
![image](https://user-images.githubusercontent.com/547626/31871740-846799e6-b76b-11e7-9b5c-422eaa00e36a.png)

gbXML import into Open Studio for all shapes progressing well. Opening, overhangs and interior space floor: to be completed,

![image](https://user-images.githubusercontent.com/547626/31871881-45f964c2-b76c-11e7-9f0a-052e0ae61294.png)

## [Read Me]( https://github.com/ladybug-tools/spider/tree/master/sandbox/build-well-qline )

Having all the shapes visible simultaneously is making debugging a lot easier. Ditto leaving a visible gap between the floors. Production versions will have these features turned off as the default.

Looks like gbXML export will be fairly straightforward to complete. After that it will be back to the shape parameters

 ## Issues / To Do

* Floor/Space/Zone IDs currently higgledy piggledy
* gbXML openings, floors an overhangs
* Fix section parameters so origin is at lower left
* Add IDs to HUD readout
* Fix site settings issues 
* Start adding more shapes

## Change Log

* Many updates
* Coding much simpler than before means things faster and easier to fix and to dd new features
* gbXML export mostly working

**Comment by bwelle** [comment]
@theo-armour 
This is very cool! I'm a bit confused how this fits in non-side project dev efforts, Build Well geometry, gbXML export etc, seemed to have merged somewhat into a single thread, doing my best to understand, and provide comments/feedback in appropriate places...

**Comment by theo-armour** [comment]
![image](https://user-images.githubusercontent.com/547626/31929776-0fe3db60-b852-11e7-9b3d-ebfb174a293e.png)

Most of the day on gbXML
* Exporting floor, angle, overhangs and more
* Just got stuck on exporting openings
* A fresh morning brain should be able to fix this

**Comment by theo-armour** [comment]
![image](https://user-images.githubusercontent.com/547626/31968060-baaa4e4a-b8c4-11e7-8b78-f41a540970a4.png)

14:08 PST

Open Studio is reading all Build Well qLine vertices. Should work with every shape you can imagine.

Do you need a shape for every letter in the alphabet? You can have. Klingon alphabet?? No sweat.

Wait, wait, but we're not finished.

There's still diaginal walls and roof over interior space to add, but these all use vertices we already have.

And then there's all the adjacencies to add. The Klingon 'D' is not going to be easy:

![image](https://user-images.githubusercontent.com/547626/31968466-0dec6704-b8c6-11e7-8f9c-23be47131700.png)


;-)

Fingers crossed the remaining 'housekeeping' tasks do not take long .

Once the gbXML in qLine is OK,  the qLine code can be folded into the main Build Well stream.

You will be notified when gbXML files you can test are ready to look at.

**Comment by bwelle** [comment]
@theo-armour @antonszilasi 

We only plan to support Box, T, U, H, Plus, L, and donut for our v1 release of SPEED. These constitute about 90% of the shapes architects will want to play with. 

But...the Klingon D would be pretty bad ass....;)

**Comment by theo-armour** [comment]
![image](https://user-images.githubusercontent.com/547626/31972045-87d23cb2-b8d3-11e7-95a1-4c6040c26ec3.png)

Plus Shape
* 161 floors
* 13 spaces per floor
* 28 degree orientation
* 88% WWR
* 10' overhangs
* 20' interior depth
* 8 adjacent structures
* 10.3 MB file / 333,000 lines

Loads in gbXML Viewer in under 10 seconds

( And it looks like some debugging test geometry got in there somewhere - adding extra geometry to load.)

**Comment by bwelle** [comment]
So cool! How does this visualization/generation method differ from the original Build Well? Is a fundamentally new way of visualizing geometry?

**Comment by bwelle** [comment]
@theo-armour 
What I like about this is that you can use two parameters, length and width, to drive all footprints. That's how the new logic in that excel spreadsheet is set up, just with certain Length and width constraints to maintain square footage and some logic on how to "morph" the shape. I'm trying to envision the best way this "view" of many footprints in a single display could be best utilized from an architect's perspective...

**Comment by theo-armour** [comment]
## [Build Well qLine R1.4 ]( http://ladybug-tools.github.io/spider/sandbox/build-well-qline/index.html )

## Change Log

* gbXML exporting most all geometry
	* And it's appearing in gbXML Reader and Opon Stdio
* IDs are progressing
* Adjacency elements are just place holders for the moment

**Comment by theo-armour** [comment]
@bwelle 

> What I like about this is that you can use two parameters, length and width, to drive all footprints. 

Actually the area input box is grayed out. I was trying to indicate that it's currently dysfunctional until I add in your logic. 

;-)

>  How does this visualization/generation method differ from the original Build Well? Is a fundamentally new way of visualizing geometry?

Build Well R12 and before consider each space individually. Every space has its own function with its own code. This was fine with a box - with 4 functions and even the L shape with six functions is OK. But then the Plus shape would have 12 functions all to itself. Want to change something and you have to edit every single function. I think there have to be 64 function to maintain just to do the nine examples. This gets to be a headache.

The qLine way treats the exterior as a thing to be extruded. A single function handles all the twists and turns. I could explain in much more detail, but I think you might prefer if I coded new stuff instead.

![image](https://user-images.githubusercontent.com/547626/31983223-404b4562-b911-11e7-911a-502d59d26570.png)
