### ISSUE TITLE
2017-10-26 ~ Update ~ Build Well qLine 2.0 ~ real-time parametric updates for 8 of 9 shapes 

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#53]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/32089576-a5c5077c-ba9f-11e7-9ea4-6d45944da03b.png)

## Full Screen: [Build Well qLine  R2 Dev]( http://ladybug-tools.github.io/spider/sandbox/build-well-qline/dev/index.html )

I have this fear that deep down inside there is some huge thing wrong with the code. Then again it's only a demo. To paraphrase Duke Ellington: “If it looks good, it IS good.”

 
## Change Log

BW qLine 2.0
* Geometry parameterization looking quite good
	* Change area / Length is static / width updates
	* Change length / area static / width updates
	* Two controls only 
	* 8 out of 9 shapes covered <O shape has issues caused its concavity>
	* All shapes visible and updated in real time
* Shape Editor now in SI units
	* US units menu soon

**Comment by mdengusiak** [comment]
@theo-armour 
I was away for a week and can see lots of new stuff :)
1. I like new naming and numbering, please start with Floors from 0 as Ground Floor and keep spaces from.In fact I would start from 00 but I guess you store them as numbers for not possible..
![2017-10-28 20_38_56](https://user-images.githubusercontent.com/14005893/32137950-e6330ede-bc21-11e7-804c-478f1915c10f.png)

2. Love to see units :) , please add this everywhere!
![image](https://user-images.githubusercontent.com/14005893/32137915-0e53cc92-bc21-11e7-9066-25293dc1315f.png)

**Comment by theo-armour** [comment]
@mdengusiak 

> please start with Floors from 0 as Ground Floor

how about storeys start with zero in SI units and at 1 in USA units?

BTW, I am slowly switching my brain ( and code ) to 'storeys' instead of 'floors. because gbXXML likes storeys

> 2. Love to see units :) , please add this everywhere!

These will come in menu by menu - whenever I have to do other updates to the menu.

> 3.Great to see Metric version 

Have a look at 
http://www.ladybug.tools/spider/build-well/r13/mnu-shape-editor.html

I would like to build this menu in German - as a demo. Can you supply suitable German text for the inputs? You can ignore comments and temporary text.

**Comment by bwelle** [comment]
@theo-armour @mdengusiak 
Please have floors start from 1. This is convention here in the US, and how we've based the rest of our code in SPEED already developed. If storey 1 does not match "Floor 1" in other parts of our GUI, it will mislead and confuse architects. I'm happy to revisit this topic later if there is a compelling reason, but for now that's we need for our technology stack and demo.

**Comment by bwelle** [comment]
@mdengusiak 
I in general very much appreciate your input into the export development process and welcome the fresh ideas, but this export dev originally started as something for Build Well in preparation for a demo to our leadership next month to be able to get funding for future development. The more focused we can remain on our critical path items, the greater the chances we all can continue to work on things like this together. If you could bear with me until critical path items are completed, I'd greatly appreciate it, and hopefully once a successful demo is complete, we can more freely ideate, innovate, and collaborate.

**Comment by bwelle** [comment]
@theo-armour @mdengusiak 
As long as US Shape Editor has Level 1=Storey 1=Floor 1, I'm happy.:)

Metric version you may defer to Mike.

Good compromise?:)
