### ISSUE TITLE
gbXML / Build Well / where to record azimuth?

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#54]
@bwelle 

For calculations you need to carry out for you upcoming events, you need to know the angle or orientation for every space or zone.

I see nothing in the gbXML Schema 6.01 about adding angles to either of these.

It seems the logical place to add this would to include a rectangular element with an azimuth attribute as the only sub-element to surface elements.

For the immediate time frame, would it be OK and sufficient to add azimuth data just to ExteriorWall surfaces? [Of course, full rectangular data will be added later.]

**Comment by bwelle** [comment]
@theo-armour @antonszilasi 

I don't need to know the angle or orientation for spaces or zones. That concept doesn't exist in gbXML or energy modeling. Just the azimuth of the bounding surfaces, which in this case are exterior walls and the child windows. It's fine for now to add azimuth to those surface definitions, but it seems not that much more difficult just to add rectangular geometry definitions. Once you know the azimuth and normal, you simply take lower left polyloop coordinate I believe, then define surface height (equal to the parameter Floor Height in our case, or take two polyloop points with same x,y coordinates and look at the delta Z, then for surface length, take the two coordinates with the low Z coordinate and calculate it's length...I assume there's a function in three.js to calculate the length of two coordinates. Anyway, most critical part is azimuth somewhere for the surface. Anton, maybe you could add the Rectangular Geometry for Theo so he can move on to other things?

**Comment by bwelle** [comment]
closing as Anton will specify shortly where to put azimuth.
