### ISSUE TITLE
Build Well Q-line Integration Issues

### ISSUE THREAD

**Issue by bwelle** [ladybug-tools/spider#55]
As there is no issue directly linking to R13.4 here to comment bugs/issues, I've created this issue to do so.

**Comment by bwelle** [comment]
In general, with the integration of new Q-line logic into Build Well, much of the previously working gbXML export no longer works. I will summarize the issues I see here. Feel free to break out individual bugs to separate issues if you wish.

1. When you export the gbXML file, all the other "shapes" are coming through as shading boxes. You will want to eliminate that first.

2. When I look at the space for single floor L-shape export, (should be 7), your export puts 14 as if it was two floors, then another 7 for a total of 21 spaces.

3. If you put to 1 floor (usa editor) and pick l-shape under zones menu, you can see the extra zones listed, which oddly enough is different than what is exported. The view shows zones 1-5 then 1-7 (12 total) while export has 21 zones (sometimes, but sometimes it's correct with 7 but zone list always shows the same thing).

4. I tried this export a second time, and all of sudden it showed the correct number of zones (7), but it exported and imported into OS with a box shading building overlapping the L-shape. Not sure why the inconsistency in export bugs.

5. The space numbering, clockwise, which used to work in previous Build Wells is now reverse,
it's counterclockwise.

6. I exported a third time, and new bugs popped up. There should be only 6 windows exported for single floor L-Shape, but I see this in gbXML file:

  <Opening openingType="OperableWindow" id="bw-opening-14" >
<PlanarGeometry>
<PolyLoop>
<CartesianPoint>
<Coordinate>103</Coordinate>
<Coordinate>285</Coordinate>
<Coordinate>9.84</Coordinate>
</CartesianPoint>
<CartesianPoint>
<Coordinate>103</Coordinate>
<Coordinate>285</Coordinate>
<Coordinate>2.16</Coordinate>
</CartesianPoint>
<CartesianPoint>
<Coordinate>60.3333</Coordinate>
<Coordinate>285</Coordinate>
<Coordinate>2.16</Coordinate>
</CartesianPoint>
<CartesianPoint>
<Coordinate>60.3333</Coordinate>
<Coordinate>285</Coordinate>
<Coordinate>9.84</Coordinate>
</CartesianPoint>
</PolyLoop>
</PlanarGeometry>
</Opening>
</Surface>

I see that showing a 14th window. Seems like it's trying to export surfaces/spaces from other shapes?

7. Previously the shape exported was centered around global axis at centerline of x and y extents, then updates to geometry maintained that spacing. One time I exported single floor L-shape,  and the shape stays where ever it was with coordinates relative to 9 other shapes (meaning no where close to origin of axes. Another time I exported, and it overlapped the axes, but not centered at x and y extents. Again, no idea why the inconsistencies, I use exact same inputs in USA builder.

8. You assign things like spaces and surfaces to floor 1/storey 1 but you have storey 1 at Level 0. For clarity, please just make it Level 1.

9. Zone 7 area and volume the same:

<Space id="bw-space-7" buildingStoreyIdRef="bw-storey-1" zoneIdRef="bw-zone-7" conditionType="HeatedAndCooled" >
<Name>Floor: 1 Space: 7</Name>
<Description>internal space</Description>
<Area>23</Area>
<Volume>23</Volume>

10. I see in the gbXML file for L-Shape it's trying to export T-Shape surfaces (and U, and Donut, and H, etc.:

		<Surface surfaceType="Shade" id="bw-shade-1" >
			<Name>T shape</Name>
			<PlanarGeometry>
				<PolyLoop>
					<CartesianPoint>
						<Coordinate>464</Coordinate>
						<Coordinate>464</Coordinate>
						<Coordinate>0</Coordinate>
					</CartesianPoint>
					<CartesianPoint>
						<Coordinate>596</Coordinate>
						<Coordinate>464</Coordinate>
						<Coordinate>0</Coordinate>
					</CartesianPoint>
					<CartesianPoint>
						<Coordinate>596</Coordinate>
						<Coordinate>464</Coordinate>
						<Coordinate>12</Coordinate>
					</CartesianPoint>
					<CartesianPoint>
						<Coordinate>464</Coordinate>
						<Coordinate>464</Coordinate>
						<Coordinate>12</Coordinate>
					</CartesianPoint>
				</PolyLoop>
			</PlanarGeometry>
		</Surface>

11. Should be 32 surfaces (excluding openings). File has 33.

12. You name openings with IDs the same number as the parent surface. Openings should start with and ID of 1 then increment upwards. 6 windows means bw-opening-1, bw-opening-2...bw-opening-6.

It might be useful to separate out "qline view of 9 shapes, and have one other tab where it has the single building like before, but the user can select which shape they want to show up as base, rather than standard having all 9, then allow gbXML export to be based off that view/tab
next observation,

**Comment by theo-armour** [comment]
@bwelle 

### Build Well gbXML Export
I am currently building a gbXML data checker that may be run from inside gbXML export. Fingers crossed to helps spot many of the above and thus speed up the debug process.

### Open Studio
I have yet to have success in getting a gbXML file to 'Run' in Open Studio. I have tried exporting their sample file as a gbXML file and then importing it. It too fails.

I am attaching a San Francisco EPW file prior to the run. I am able to create the OSM template. but the process fails and I get missing construction name errors.

So what else do I need to attach to the session or to do in order for this Open Studio Run thing to comple successfully?

And does this Run thing have a name I can Google?

**Comment by theo-armour** [comment]
_see previous comments_

### Build Well gbXML Export

Error checker in BW R14. Found errors and fixed 'em.

### Open Studio

The 'Run' thing - if you can read the small text - is called 'Run Simulation'. Now as to what it does or accomplishes: your guess is as good as mine. ;-)

I actually got it to run and complete - just once out of a dozen or so attempts. Of course once I did it, I thought I could do it over again. So I wrote over the successful run and have no proof.

The magic seems to be in the order or manner in which you do things. I have not yet found which magic wand is the right one to use,
