### ISSUE TITLE
spider/cookbook/SPEED Geometry Requirements/

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#60]
@bwelle @antonszilasi 

### https://github.com/ladybug-tools/spider/tree/master/cookbook/SPEED%20Geometry%20Requirements

> 8. Theo, the grid extents still don't auto update when placing adjacent buildings. Please advise how to do this.

The code I used is in R12

https://github.com/ladybug-tools/spider/blob/master/build-well/r12/mnu-adjacent-buildings.html#L282-L291

***

> 1. Anton, enable overhang depth for geometry. Theo has example.
> 2. Anton, enable fin depth for geometry. You should be able to figure this out once overhang depth is done.

This file has sample code:

http://www.ladybug.tools/spider/cookbook/multiple-openings/wall-with-multiple-openings-overhangs-fins-r1.html

![image](https://user-images.githubusercontent.com/547626/32823640-bce91c70-c992-11e7-998a-08064d74686f.png)

**Comment by antonszilasi** [comment]
@theo-armour 

Many thanks for the example, it is very neat indeed. Unfortunately I am having a hard time integrating this example into the createQlineMesh function which can be seen [here](https://github.com/antonszilasi/spiderAnton/blob/master/speed/geometry.js#L740-L941) (which is essentially the same as your original qline function.

Essentially the struggle resolves around the lines of code 

```
			const verticesOpening = geometryBoundary.clone().scale( wwr, wwr, wwr ).vertices.slice( 0, -1 );
			const hole = new THREE.Path();
			hole.setFromPoints( verticesOpening );
			shape.holes.push( hole );
```

**Comment by theo-armour** [comment]
@antonszilasi 
We texted about this privately - regarding a cookbook script I had written aimed at solving some of these issues. We seemed to mis-communicate a bit, so I just went ahead with R2 which draws Three.js Shapes above a polygon composed of arbitrary vertices. 

![image](https://user-images.githubusercontent.com/547626/32913033-ebf0a18a-cac5-11e7-9823-42ddd9f85e0e.png)

## [line with objects between vertices r2]( http://www.ladybug.tools/spider/cookbook/line-with-objects-between-vertices/line-with-objects-between-vertices-r2.html )
## [Read Me]( https://github.com/ladybug-tools/spider/tree/master/cookbook/line-with-objects-between-vertices ) << with further notes

**Comment by theo-armour** [comment]
@antonszilasi 

> Unfortunately I failed to create a shape which I could see from the vertices, (very difficult to debug if you cant see it) 

I agree. That is why from time to time I add little Three.js box meshes at vertex locations - so as to make them visible and thus be able to confirm that the little buggers are or are not where I expected them to be.
