### ISSUE TITLE
Update 2017-12-02 ~ gbXML Viewer R8.1

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#63]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/33523051-d6171936-d7b1-11e7-8ecb-1ff471c153bb.png)

## [gbXML Viewer R8.1]( http://www.ladybug.tools/spider/gbxml-viewer/r8/gbxml-viewer8-app/gbxml-viewer8-app.html )

The app is beginning to have some nice aspects and there's much more on the way.

There's way too much that's happened since the last post, we let's just start with today:

* The highlighting of spaces now shows all the surfaces 
* Non-highlighted spaces are shown using edge meshes rather than a wireframe material
* There were bunches of changes in many of the files - mostly to clean-up the code and make the names of things clearer
* All the read me files and the module test cases were updated

Probably every file in the release was touched in some way today. Many of the changes were related to renumbering text in links to handle the new release. Fingers-crossed this release-processing is mostly complete and we can get back to adding new features nice and fast

***

Look, gbXML Viewer is helping find errors in our [own scripts]( http://www.ladybug.tools/spider/#cookbook/07-create-exportable-buildings/README.md ). Yay!

![image](https://user-images.githubusercontent.com/547626/33523228-45a7920e-d7b6-11e7-8acd-9c2be48ba007.png)

**Comment by theo-armour** [comment]
## [gbXML Viewer R8.2]( http://www.ladybug.tools/spider/gbxml-viewer/ )

![image](https://user-images.githubusercontent.com/547626/33531422-af312db2-d841-11e7-992f-3b0ef1a25985.png)

Highlights surfaces with
* Duplicate coordinates
* Duplicate CAD Object IDs
* Duplicate Adjacencies  << and the space they are in
* Spaces smaller than 2 square units < and the space they are in

**Comment by theo-armour** [comment]
## [gbXML Viewer R8.3]( http://www.ladybug.tools/spider/gbxml-viewer/ )

![image](https://user-images.githubusercontent.com/547626/33589690-2529cc70-d92f-11e7-9ca1-424147e011ec.png)

Little fixes and new features everywhere

* Add buttons to Heads-up display - but need ti re-think the user interaction. Probably turn into click-to display and readout in right menu
* Add choices to Settings
* Add surface, edges and rest buttons to Core

Items form To Do list completed or well underway

* 2017-12-02 ~ Michal: Zoom and center duplicate surfaces, duplicate coordinates, tiny surfaces
* 2017-12-01 ~ Add better display = none on new file loaded
* 2017-12-01 ~ Add hamburger/slider menu
* 2017-12-01 ~ Michal: Locate camera/controls target inside a given space / zoom into the space

**Comment by mdengusiak** [comment]
@theo-armour 
THANK FOR amazing work. Seems you are on the case so  I am back. I hope we will make the most amazing gbXML viewer/fixer ever.

here are comment:

![image](https://user-images.githubusercontent.com/14005893/33600269-ac55c87c-d9a0-11e7-8027-8238999dfe8e.png)

![image](https://user-images.githubusercontent.com/14005893/33600497-4e9222c0-d9a1-11e7-84bb-e9e4f37ea7ca.png)

![image](https://user-images.githubusercontent.com/14005893/33600383-fedd865c-d9a0-11e7-8444-6e129f10c463.png)

![image](https://user-images.githubusercontent.com/14005893/33600455-3057d16a-d9a1-11e7-893a-c0046e4c9815.png)

![image](https://user-images.githubusercontent.com/14005893/33600578-90ee2704-d9a1-11e7-8462-251ccc7dfa9b.png)

![image](https://user-images.githubusercontent.com/14005893/33600685-ddee08c6-d9a1-11e7-87a8-78cb9f86ccb1.png)

**Comment by theo-armour** [comment]
@mdengusiak 

Many thanks for your easy to read (and easy to fix ) list.

I believe that many of the items have been dealt with in this release:

Resizing heads-up is there but very unstable.

## [gbXML Viewer R8.4]( http://www.ladybug.tools/spider/gbxml-viewer/ )

The main item not addressed is that last item - which I am not sure I understand completely.

Currently the viewer list all the surface types listed in the file. If it's there then its listed.

I am thinking of adding a settings feature that would add a ground surface to the display. This would receive shadow etc. Would that help? Or maybe we should talk things over if I am missing something.

**Comment by mdengusiak** [comment]
Thanks @theo-armour for great chat I hope now everything is clear...
Here is sample one space gbXML export fro reference:
[Building1.zip](https://github.com/ladybug-tools/spider/files/1537215/Building1.zip)

**Comment by theo-armour** [comment]
@mdengusiak 

App2 R8.5
12:44
* Fixed: reset view not resetting surfaces visible
* Settings: add toggle grid
* Settings: add toggle ground
* App2: add footer

* 2017-12-01 ~ Add a 'ground' that can receive shadow

8.6
21:32
* Fix some of the reset view issues
* Highlight all duplicate adjacencies in red
* Add better spacing between duplicate adjacencies log
* Tiny surface telltale now has opacity - so you can see very tine things inside the telltale
* location hash and splash screen working together better
* Add button to turn off heads-up - not yet a nice toggle

**Comment by theo-armour** [comment]
@mdengusiak 

![image](https://user-images.githubusercontent.com/547626/33746855-94a4e6ec-db74-11e7-8eb5-a51e243a2027.png)

## [gbXML Viewer R8.7]( http://www.ladybug.tools/spider/gbxml-viewer/ )

* Templates: code clean-up
	* Add drag and drop capability
	* Better selection of sample files
* Settings:
	* Add set color by exposure type
	* Add drag and drop capability
	* Better selection of sample files
* Reports
	* Add drag and drop capability
	* Better selection of sample files
	* Add view storey
	* Add is a space has an 'InteriorFloor' or 'SlabOnGrade' or 'RaisedFloor' or 'UndergroundSlab' then zoom into that space
* App2
	* Add drag and drop capability

Done

* 2017-12-01 ~ Load files via drag and drop
* 2017-12-02 ~ Add test file??
* 2017-12-01 ~ Add choice to display in right-side menu

**Comment by mdengusi** [comment]
this is great.. drag works excellent 
I love storey

1. reset does not reset : background gradient , materials colors or camera ortho

![image](https://user-images.githubusercontent.com/26113670/33762074-25832208-dc03-11e7-9dad-b0f9a2a1683f.png)

2. Is there any chace to almost replicate in storey view - floor plans with space name and number

![image](https://user-images.githubusercontent.com/26113670/33762288-d69caabe-dc03-11e7-8bad-32db93a7fd6e.png)

3. Storey ability to hide roofs or floor to better see layout
![image](https://user-images.githubusercontent.com/26113670/33762319-f759ee42-dc03-11e7-858f-ade4a3e737b9.png)

4. can we show number of zones per storey
![image](https://user-images.githubusercontent.com/26113670/33762380-27c46328-dc04-11e7-8573-02561be01ab9.png)

**Comment by mostaphaRoudsari** [comment]
This is awesome! I needed a quick gbXML viewer today and worked great for me! :)
![image](https://user-images.githubusercontent.com/2915573/33797946-ac8d6764-dcde-11e7-8e23-48f425841d9e.png)

**Comment by theo-armour** [comment]
@mdengusiak 

![image](https://user-images.githubusercontent.com/547626/33799191-a4f24f4a-dcdb-11e7-9ba2-389e1739df38.png)


R8.9
* Core
	* Add 'reset view' calls createReport() 
* HUD
	* Add toggle button
	* Toggle off when new file loaded

R8.8
* Core
	* Add 'reset view' button resets background, camera, material colors
* Reports
	* Add toggle visibility for each surface type
	* Add display zone count and names per storey

Note
'reset view' button not currently working in reports, so has been disabled for the moment

Done
* 2017-12-07 ~ Michal: toggle for HUD
* 2017-12-08 ~ Michal: reset view: includes background gradient , materials colors or camera ortho
* 2017-12-08 ~ Michal: Storey ability to hide roofs or floor to better see layout
* 2017-12-08 ~ Michal: can we show number of zones per storey?

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

The script takes gbXML data and turns it into JSON. Do any of your apps read/write to JSON? Or read/write to gbXML?

**Comment by mdengusi** [comment]
@theo-armour 
Hi progress is amazing....

1. reset works great now the only one that is not resetting is 
after `Set Camera to Ortho`  

2. can we change color for inside surfaces to RGB(255,128,128)
![image](https://user-images.githubusercontent.com/26113670/33799688-5a5214a0-dd28-11e7-8834-2b4161cfee9a.png)
other colors are:
 exposed RGB(128,255,128)
adiabatic  RGB(192,128,255)
ground RGB(208,104,0)
adiabatic  RGB(128,255,128)

3. can we show normals for selected items only
![image](https://user-images.githubusercontent.com/26113670/33799703-d70189d6-dd28-11e7-99fb-2089b5055eef.png)

4. can we swtich off shadows
![image](https://user-images.githubusercontent.com/26113670/33799719-36be51ba-dd29-11e7-98bb-6498bd8e8d98.png)

5. would be nice to operate them when level (storey) is selected only on this object switch off and on different surfaces
![image](https://user-images.githubusercontent.com/26113670/33799737-83dae7c4-dd29-11e7-8137-ed38267eb3d3.png)

6.this is great we can see odd one out
![image](https://user-images.githubusercontent.com/26113670/33799744-a524979a-dd29-11e7-88df-17887b496f54.png)

7. this new feature is unique and amazing, I guess we could connect to some game engine and play based on our own building as a break from working - --- THIS IS AWSOME!!!!!

I can see straight away that there are some keyboard keys working...can you send me full keyboard shortcut keys and explanation I can see that: A,S,R,F are doing something...
![image](https://user-images.githubusercontent.com/26113670/33799758-f395cd90-dd29-11e7-967c-f3db9797b9e2.png)

8. can we make that when is blue is ON and is grey is off...at the moment there is many option posible depends how we click
![image](https://user-images.githubusercontent.com/26113670/33799810-15c2a1e4-dd2b-11e7-8d2a-0106ed047261.png)

9. would be cool to work on e`xposure surface types` same way as on surfaces types with ON and OFF

**Comment by mostaphaRoudsari** [comment]
> The script takes gbXML data and turns it into JSON. Do any of your apps read/write to JSON? Or read/write to gbXML?

@theo-armour, yes! Honeybee does. We're currently using OpenStudio libraries to import/export gbXML. Can you direct me to the parser code? Converting to JSON making it easier to parse.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

All the heavy lifting is in this stand-alone HTML file with the actual parser function highlighted:

https://github.com/ladybug-tools/spider/blob/master/gbxml-viewer/r8/gbxml-viewer8-01-core/gbxml-viewer8-core-r3.html#L250-L307

And, frankly, there's not much heavy lifting to be done. ;-)

**Comment by mdengusi** [comment]
@mostaphaRoudsari 
This sounds now very interesting apart from viewing gbXML and showing errors and issues with gemometry we want aslo try to fix some of them  and open new ways of collaborations.
I am thinking about this:
1.  ability to transform JSON to gbXML, gbXML to JSON
2. Allow Honeybee/Ladybug to import one space form whole gbXML/JSON that allow us to run detail Butterfly or Radians calcs...
2a. In fact wound be amazing to bring results back so calculate space and display in our Viewer.... whole building but also details for selected space so we can see for which space simulation where done and how does it look in whole context
3. Could we use honeybee/ladybug to open gbXML/JSON file directly form `gbXML viewer` ?
This is super fast to see changes and review quality of file and spot all problems with geometry

I guess first of all we want:

- [ ]  to make viewer as good as possible from operational point of view to ma sure easy to use and usefull
- [ ]  adopt geometry fixing method

- [ ] establish bi-directional links to various tools 
- [ ] allow to store space results data to visualize results
- [ ] *make game that allows us  run though our building and enjoy what we did

* I call it verification and enjoyment mode as we can see if building make sens if we can walk though it. 

@theo-armour pease let me know what do you think and if agree with my vision

ps. I come across this task list approach that we can tick boxes I will try to use it from now on as we can easily monitor what was completed)

**Comment by mdengusiak** [comment]
@mostaphaRoudsari 
This sounds now very interesting apart from viewing gbXML and showing errors and issues with gemometry we want aslo try to fix some of them  and open new ways of collaborations.
I am thinking about this:
1.  ability to transform JSON to gbXML, gbXML to JSON
2. Allow Honeybee/Ladybug to import one space form whole gbXML/JSON that allow us to run detail Butterfly or Radians calcs...
2a. In fact wound be amazing to bring results back so calculate space and display in our Viewer.... whole building but also details for selected space so we can see for which space simulation where done and how does it look in whole context
3. Could we use honeybee/ladybug to open gbXML/JSON file directly form `gbXML viewer` ?
This is super fast to see changes and review quality of file and spot all problems with geometry

I guess first of all we want:

- [ ]  to make viewer as good as possible from operational point of view to ma sure easy to use and usefull
- [ ]  adopt geometry fixing method

- [ ] establish bi-directional links to various tools 
- [ ] allow to store space results data to visualize results
- [ ] *make game that allows us  run though our building and enjoy what we did

* I call it verification and enjoyment mode as we can see if building make sens if we can walk though it. 

@theo-armour pease let me know what do you think and if agree with my vision

ps. I come across this task list approach that we can tick boxes I will try to use it from now on as we can easily monitor what was completed)

**Comment by theo-armour** [comment]
@mdengusiak 

> can we swtich off shadows?

This is likely to be part of an Analemma/light/shadow settings menu

> would be nice to operate them when level (storey) is selected only on this object switch off and on different surfaces

Yes, the interaction get complicated. We need to play with the interaction some more and come up with some logical 'rules'. What we don't want to do is keep adding buttons and UI widgets. What we want is a few simple interactions that take care of most everything. Let's us continue playing and interaction with what is there for a while. And after some decide some new rules.

> this is great we can see odd one out

We need different colors for the different odd things. And some good rules for finding these types of things.

> adiabatic

The definition of adiabatic is 'relating to or denoting a process or condition in which heat does not enter or leave the system concerned.'
 ;-)

I need a better sense of what 'adiabatic' means in terms of setting colors of walls or finding issues.

***

I think many of the other points you raise are covered in R8.9 and R8.10

**Comment by mdengusiak** [comment]
@theo-armour  I am speachless --thanks for solving many comments!!!!!
Love it!!!

![viewert](https://user-images.githubusercontent.com/14005893/33824512-87f81fa6-de56-11e7-9a6c-0a6575a945ad.gif)


1. I like you managed to get now underground surfaces
![image](https://user-images.githubusercontent.com/14005893/33823668-d28c9a7c-de53-11e7-812c-07a69b54e804.png)

2.  ok shadows we are not crucial I think this will be solved with your new sunpaths feature..

3. `Adiabatic` is  **internal** surfaces that do not have two **different** spaces Adjaciencies

4. In version 8.10 head up does not work
![image](https://user-images.githubusercontent.com/14005893/33823810-46ba3f62-de54-11e7-8c9e-bc3df1d0d1a1.png)

5. `Set exposure Type material ` this is for surrunging building and context
can we change color for Shade to RGB(255,180,128)
![image](https://user-images.githubusercontent.com/14005893/33824750-4c6b8d0a-de57-11e7-814e-a6cfdfbbbb63.png)
