### ISSUE TITLE
Editing Files

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#64]
@chiensiTB 

[create-exportable-buildings.html]( https://github.com/ladybug-tools/spider/blob/master/cookbook/07-create-exportable-buildings/create-exportable-buildings.html )

I have just had a look at this file.

I note that you have merged a number of edits into the file.

I am happy that you are taking the time and effort to improve the script.

Please note, however, that the usual way to collaborate is to fork a file and make edits on the new copy,

If you wish to edit the original file, it's best to seek an OK from the authors first and agree methods of collaboration prior to committing.

**Comment by chiensiTB** [comment]
I've forked it.

**Comment by chiensiTB** [comment]
I was in a rush, sorry, and the way this project is setup is unusual, I was trying to generate maximal value in the shortest amount of time, committing was the only way I can see my changes take effect.
