### ISSUE TITLE
Update 2017-12-10 ~ gbXML Viewer R8.9 & R8.10 

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#68]
@ladybug-tools/spiders 

## [gbXML Viewer R8.10]( http://www.ladybug.tools/spider/gbxml-viewer/ )

![image](https://user-images.githubusercontent.com/547626/33811306-8fc393f4-ddc6-11e7-9f3a-2f6fa986d562.png)
R8.10 begins to add a working analemma. It's still at a very early stage, but could not resist adding an image

![image](https://user-images.githubusercontent.com/547626/33811417-0f3d0312-ddc8-11e7-8f05-59a7b7bcba05.png)
R8.9 added a first person camera option.

Fly through and around your models. Use cursor keys or WASD keys. Click on the icons at bottom of your screen

This is a new and experimental feature.

Click on any of the files in the left menu. Once the model is loaded, you can ***click any of the icons at the bottom of the screen to get started***. After you have touched or clicked an icon you may also start to use your keyboard keys.

Your pointing device works as usual. You can pan zoom and rotate as you do normally

To help you navigate the model - which is not always easy - there is a 3D avatar. She is a large baby tadpole. Her name is 'Gypsy' Emily as in: G-B-X ( pronounced like a Z) followed by an Em and an Ell. In other words she is the embodiment of gbXML.

**Comment by mdengusi** [comment]
@theo-armour 

Hi as we discussed here new comments under new version:

1. can we group `Duplicate CADObjectId`
at the top will be 
![image](https://user-images.githubusercontent.com/26113670/33905866-f4d8f90c-df77-11e7-967b-ba5bd9291b27.png)

![image](https://user-images.githubusercontent.com/26113670/33906041-8ea3d96c-df78-11e7-9c95-1cc9d8f4ee24.png)


something like:
![image](https://user-images.githubusercontent.com/26113670/33905999-7843058a-df78-11e7-8696-3617e4a2a2a3.png)

2. I am struggling to get to working for any files above 30MB normally gbXML can get up to 350 MB. This is for me **fundamental** issue and we need to find solution for large files

3. finally I have model with from Revit that produced air..
can you please change exposure type `Air `to color `RGB(255.255,128)`
Default material is correct color. 
![image](https://user-images.githubusercontent.com/26113670/33906290-6f338d60-df79-11e7-8e6c-4948d875e15b.png)

4. I think exposure type colors for floors are now broken, it was correct before
![image](https://user-images.githubusercontent.com/26113670/33906475-009b865e-df7a-11e7-8a06-d258367523e1.png)

5. could we get option to quickly change between default materials and analysis mode?
![image](https://user-images.githubusercontent.com/26113670/33906769-ce51f420-df7a-11e7-9c1d-f47a5c8be72a.png)

thanks

**Comment by theo-armour** [comment]
@mdengusiak 

Thank you for your good suggestions.

> 1. Duplicate CADObjectId
I will look into this in the next day or so. 

Also we might might have a chat about this item. Am I correct in thinking that there is nothing to be fixed here? And that the multiple elements in the gbXML file are simply the result of the translation process from the CAD program?

> 2. I am struggling to get to working for any files above 30MB normally gbXML can get up to 350 MB. This is for me fundamental issue and we need to find solution for large files

Can you supply some large files. The one we looked at a few weeks ago have some techical issues and the xml would not even load into the browser.

> finally I have model with from Revit that produced air. can you please change exposure type Airto color RGB(255.255,128)

See GV 8.11

> 4. I think exposure type colors for floors are now broken, it was correct before

Here is the current set of colors - in hex.

	function setExposureMaterial2() {

		var colorsExposure = {

			InteriorWall: 0xff8080,
			ExteriorWall: 0x80ff80,
			Roof: 0x80ff80,
			InteriorFloor: 0xff8080,
			ExposedFloor: 0x80ff80,
			Shade: 0xffb480 ,
			UndergroundWall: 0xd06800,
			UndergroundSlab: 0xd06800,
			Ceiling: 0xff8080,
			Air: 0xffff80,
			UndergroundCeiling: 0xff8080,
			RaisedFloor: 0xff8080,
			SlabOnGrade: 0xd06800,
			FreestandingColumn: 0xff8080,
			EmbeddedColumn: 0xff8080

		}

> 5. could we get option to quickly change between default materials and analysis mode?

In general, the menu in the 3D is for functions in the core HTML file  and the menus in the left menu are for code in standalone JavaScript files. The includes the Settings JavaScript.

Of course, we can put anything we want anywhere, but let's do this when we really know what are the primary shortcuts real users will really be needing.

**Comment by theo-armour** [comment]
@ladybug-tools/spiders 

## [gbXML Viewer R8.11]( http://www.ladybug.tools/spider/gbxml-viewer/ )

![image](https://user-images.githubusercontent.com/547626/33917330-8ce24d36-df62-11e7-993f-ba3a81342a1f.png)

* Reports
	* Updated to button tag
	* Storeys: display number and IDs of spaces
	* Surfaces
		* Better handling of on/off toggles
		* Add 'all visible' button
	* Duplicate Coordinates
		* Add visibility toggle for all duplicates
		* Add Space button to toggle view of space
	* Duplicate Adjacencies
		* Add visibility toggle for all duplicates
		* Add length and width of element
	* Tiny Surfaces
		* Add length and width of element
	* Invalid Adjacencies << new item
		* Checks for multiple adjacencies in objects that should only have a single adjacency
* Settings
	* Add toggle buttons for surfaces/edges/all
	* Update colors
	* Colors of duplicates etc unchanged when toggling other color settings
* Many other minor fixes and code clean-up
