### ISSUE TITLE
Update 2018-01-01 ~ gbXML Viewer R9 ~ new user experience + create animated GIFs

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#72]
@ladybug-tools/spiders 

![ezgif com-optimize](https://user-images.githubusercontent.com/547626/34473733-288d1f2c-ef2b-11e7-8476-cb42f6eb250e.gif)
_Let your gbXML files come alive_

## [gbXML Viewer R9.0]( http://www.ladybug.tools/spider/gbxml-viewer/ )

Happy new year!

Please welcome gbXML Viewer R9 with its redesigned user experience.

The big new feature is the screen capture utility. Now you can create animated GIFs from your files.

The above example kind of sucks, but that just leaves lots of room to get better.

**Comment by mdengusi** [comment]
@theo-armour 
Thanks a lot, Theo, definitely right direction :)
I am using version 9.1

1. Reset view does not work after Toggle Camera Ortho and after sun-path. In fact, I can not switch off sun-path at all.
![image](https://user-images.githubusercontent.com/26113670/34644937-ff2f8676-f338-11e7-9966-4b86546cdec3.png)

2. also In Toggle-Feature: `settings`, `report  `does not work always for me.  It is very random

3. surfaces does not switch ON/OFF
![image](https://user-images.githubusercontent.com/26113670/34644958-93142dec-f339-11e7-8ae6-cfc8205f41c8.png)

4. can wee move length and width to new line
![image](https://user-images.githubusercontent.com/26113670/34644972-f442b9bc-f339-11e7-87ec-015f90bcbd8e.png)

5. when exploding view, can we do not explode shade?
a. explode % does not change
![image](https://user-images.githubusercontent.com/26113670/34645127-2ffc1162-f33d-11e7-8658-83c5128773db.png)

6. reset view does not reset all cases..ie after capturing screen so I need to use Ctl+Shift+R

7. I really like screen capture... just please as first thing allows the centre of rotation which is currently the location of Axes to be adjustable...can you allow to move them
a. can we have a white background for gif
if you need sky lets use
Color Name	RGB CODE	HEX #
`Light Sky Blue`	`135-206-250`	`87cefa`
b. can we see axes in `update scene` but not during gif recording process - `capture start`?
c. can we specify location and angle of axes...I can see it goe from red to green now... 

thanks a lot

**Comment by mdengusiak** [comment]
@theo-armour 
Thanks a lot, Theo, definitely right direction :)
I am using version 9.1

1. Reset view does not work after Toggle Camera Ortho and after sun-path. In fact, I can not switch off sun-path at all.
![image](https://user-images.githubusercontent.com/26113670/34644937-ff2f8676-f338-11e7-9966-4b86546cdec3.png)

2. also In Toggle-Feature: `settings`, `report  `does not work always for me.  It is very random

3. surfaces does not switch ON/OFF
![image](https://user-images.githubusercontent.com/26113670/34644958-93142dec-f339-11e7-8ae6-cfc8205f41c8.png)

4. can wee move length and width to new line
![image](https://user-images.githubusercontent.com/26113670/34644972-f442b9bc-f339-11e7-87ec-015f90bcbd8e.png)

5. when exploding view, can we do not explode shade?
a. explode % does not change
![image](https://user-images.githubusercontent.com/26113670/34645127-2ffc1162-f33d-11e7-8658-83c5128773db.png)

6. reset view does not reset all cases..ie after capturing screen so I need to use Ctl+Shift+R

7. I really like screen capture... just please as first thing allows the centre of rotation which is currently the location of Axes to be adjustable...can you allow to move them
a. can we have a white background for gif
if you need sky lets use
Color Name	RGB CODE	HEX #
`Light Sky Blue`	`135-206-250`	`87cefa`
b. can we see axes in `update scene` but not during gif recording process - `capture start`?
c. can we specify location and angle of axes...I can see it goe from red to green now... 

thanks a lot

**Comment by theo-armour** [comment]
@mdengusiak 

All good comments. Thank you.

And they raise interesting issues. For example the sun path script add geometry that would be not useful in a a saved gbXML file. So maybe the best way to may sure everything is removed is to reload the file.

Regarding the explode and screen capture, the first thing I am looking for is that all these feature can work together. You need to be able to explode the building and do a screen capture. Or create a sun path and the screen capture. Once we know that all the new features can mostly work together then I will go back to each and fix bugs and add the rest of the features. And I still have to add a Sun range and Solar acess befor this stage is finished.

In the mean time, I am also trying to fix up the rest of the Spider site and get the whole place a bit more ready for doing some marketing.

BTW, do you ever have to use EPW files?

Theo

**Comment by bwelle** [comment]
Hi  Theo, I’d like to share with you some ideas for weather data visualization. We’d like to have a sort of “climate consultant” on the front line of SPEED, similar to the tool by the tool by the same name now. However, no one has as far as I’ve seen figured out a good way to visualize weather data (general statement) that architects can interpret usefully. Wind roses are shit, most dry-bulb/wet-bulb charts, HDD/CDD are fairly worthless….I think we can make a major disruption in this area.

**Comment by mdengusi** [comment]
Yes, we use this as main weather file format. Most of time ladybug as main visualization tool with our custom modification to way how are presented.

**Comment by theo-armour** [comment]
@mdengusiak 

> Reset view does not work after Toggle Camera Ortho and after sun-path. In fact, I can not switch off sun-path at all.

In 9.2 Reset View should be working better.

Sun path/Analemma still has no toggle. For time, just reload the file to start fresh.
 
> also In Toggle-Feature: settings, report does not work always for me. It is very random

I am having trouble reproducing these errors. Could you try again - with the JavaScript developer console open so you can see if there are any error messages to report?

I did find some things to fix. So 9.2 might be a bit better

> surfaces does not switch ON/OFF

blue button color and actual on/off get out of sync. For time being just click and look and ignore button color
  
> can we move length and width to new line?
In 9.2

> when exploding view, can we do not explode shade?
> I really like screen capture... just please as first thing allows the centre of rotation which is currently the location of Axes to be adjustable...can you allow to move them...

Yes, explode ans screen capture need many fixes. These will happen before too long.

**Comment by theo-armour** [comment]
@mdengusiak 

## [gbXML Viewer R9.3]( http://www.ladybug.tools/spider/gbxml-viewer/ )

* App R9.3
* Add Octocat link to App menu
* Change default read me from release read me to main read me
* Read me iframe link from App to Core
* Add link to release read me on menu
* Add Sun Range links to read me
* Sun Range: Add get UTC offset from Google Maps API

During our chat is was noted that the report menu loaded multiple times. That was an issue in R9.1 but was fixed in 9.2.

There is currently too much duplication between the two read me files. I will be working on cleaning this up:

http://www.ladybug.tools/spider/index.html#gbxml-viewer/README.md

http://www.ladybug.tools/spider/index.html#gbxml-viewer/r9/README.md

My recent priority has been on getting everything in [Analemma 3D]( https://rawgit.com/ladybug-tools/spider/master/analemma3d/index.html#r20/analemma3d.html ). But after yesterday's chat, I will be switching over to fixing gbXML data and saving the fixed data to a new file as the priority - along with reading and writing shell geometry. The porting of Analemma 3D features will continue at a later date. 

The other priority will be to do anything needed to help publicize the viewer.

**Comment by mdengusi** [comment]
@theo-armour 
Thanks a lot... one small item 
can we add space Name
![image](https://user-images.githubusercontent.com/26113670/35176527-91eb935a-fd71-11e7-94e9-7be2c377c4a2.png)
can not wait to see writing part working :)

**Comment by mdengusiak** [comment]
@theo-armour 
Thanks a lot... one small item 
can we add space Name
![image](https://user-images.githubusercontent.com/26113670/35176527-91eb935a-fd71-11e7-94e9-7be2c377c4a2.png)
can not wait to see writing part working :)

**Comment by mdengusiak** [comment]
@theo-armour 

I also found small bug...

1.multiple click
![image](https://user-images.githubusercontent.com/14005893/35184903-5682bd66-fdf3-11e7-91a7-990cb60dc20c.png)

2. once I select `setting `and then `reports`...I can deactivate `settings `but can not deactivate `reports`
![image](https://user-images.githubusercontent.com/14005893/35184961-0dcaa40c-fdf4-11e7-88dc-89a3a537c60c.png)

3. missing Toopit
![image](https://user-images.githubusercontent.com/14005893/35184984-a529218e-fdf4-11e7-96c3-fccb2a7a4aee.png)

4. I can switch on and off `sun-path / analemma` but it does not switch off in 3D view
![image](https://user-images.githubusercontent.com/14005893/35185007-fa4b697e-fdf4-11e7-9c58-012d1f03ea5c.png)

5. `Reset View` does not reset view after `screen capture`
![image](https://user-images.githubusercontent.com/14005893/35185021-4665216a-fdf5-11e7-83d2-17eb3c9a7e75.png)

**Comment by theo-armour** [comment]
@mdengusiak 

> can we add space Name

Added to top of 'view model' display

![image](https://user-images.githubusercontent.com/547626/35200369-e5ff3770-fec1-11e7-96db-efe547d2479e.png)

Also add selected storey name there. Needs cleaning up for when storey or space are not relevant or shown. I will continue working on this.

> once I select setting and then reports...I can deactivate settings but can not deactivate reports

I cannot seem to reproduce this error. Are you on 9.4?

> missing Tootip

Added

> I can switch on and off sun-path / analemma but it does not switch off in 3D view
> Reset View does not reset view after screen capture

Both these need much serious work. Let's ignore these for a while until after saving files is working.

> ToolTip or ReadMe Suggestion

Will add in next few updates

**Comment by mdengusiak** [comment]
@theo-armour 
I tested here OneRoom.xml file for [here](https://github.com/ladybug-tools/spider/issues/74)

1. and not sure can not see spaces
2. report seems to duplicate itself

![image](https://user-images.githubusercontent.com/14005893/35429380-b26299fe-026b-11e8-9bb4-a03275868847.png)

**Comment by theo-armour** [comment]
@mdengusiak 

Thank you for preparing the one file. it should help.

> and not sure can not see spaces

me too. will investigate.

> report seems to duplicate itself

I can now reproduce the multiple report button error. It occurs when you click 'reset view'. Will fix tomorrow

 > I noticed camera ortho changes model from my select to default one

I can't reproduce this error yet.

**Comment by theo-armour** [comment]
@mdengusiak 

![image](https://user-images.githubusercontent.com/547626/35477420-e4168bf2-0376-11e8-8e09-3ab9fa2b6e20.png)

* R9.5
* Core: drop createReport
* Reports: Fix no data for single space issue
* Reports: Fix incorrect space numbering
* App: Add onloadThreejs to clean up reports
