### ISSUE TITLE
Update 2018-01-18 ~ New Cookbook Example: Read gbXML Shell Data

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#74]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/35127410-d9f14066-fc66-11e7-9ca1-19ea93377209.png)

## Full Screen: [Read gbXML Shell Data]( http://www.ladybug.tools/spider/cookbook/read-gbxml-shell-data/read-gbxml-shell-data.html )

Feel free to request features

## Change Log

* First commit

**Comment by mdengusi** [comment]
@theo-armour 
I tested on few files and works till 45MB and 150MB and works fine

You want to test shell, rectangular geometry and then combine into main App under surfaces toggle?

![image](https://user-images.githubusercontent.com/26113670/35182251-de68a838-fdc8-11e7-90ae-88a6310a7853.png)

![image](https://user-images.githubusercontent.com/26113670/35182298-ac4d08f2-fdc9-11e7-9fb6-e5d681dfaa4c.png)

**Comment by mdengusiak** [comment]
@theo-armour 
I tested on few files and works till 45MB and 150MB and works fine

You want to test shell, rectangular geometry and then combine into main App under surfaces toggle?

![image](https://user-images.githubusercontent.com/26113670/35182251-de68a838-fdc8-11e7-90ae-88a6310a7853.png)

![image](https://user-images.githubusercontent.com/26113670/35182298-ac4d08f2-fdc9-11e7-9fb6-e5d681dfaa4c.png)

**Comment by theo-armour** [comment]
@mdengusiak 

> You want to test shell, rectangular geometry and then combine into main App under surfaces toggle?

Yes, that's the plan.

Are there other bits of data I should be considering? 

One day, the viewer will read everything in a gbXML file, but at this early stage we should establish a basic minimum that will handle most - but not all- the use cases.

**Comment by theo-armour** [comment]
@mdengusiak 

I need help verifying that the gbXML data is being correctly interpreted. In order to do this I need some very basic test cases.

Can you create simple gbXML files that have both shell and rectangular geometry? One file with just a rectangular plane. Another file with a box with different XYZ lengths.

This will help speed up getting these features into the gbXML Viewer.

**Comment by mdengusiak** [comment]
@theo-armour 

Please find attached
[OneRoom.zip](https://github.com/ladybug-tools/spider/files/1666961/OneRoom.zip)

Not sure why I could not load it here
![image](https://user-images.githubusercontent.com/26113670/35429148-add2b370-026a-11e8-909d-b8cdb5abd471.png)

**Comment by theo-armour** [comment]
@mdengusiak 

Thank you for preparing the one room file. it should help.

The file is not loading because the script expects more than one space. I will fix this tomorrow.

**Comment by theo-armour** [comment]
@mdengusiak 

![image](https://user-images.githubusercontent.com/547626/35477436-40515fdc-0377-11e8-9be7-e3bd3b7fe255.png)

**Comment by theo-armour** [comment]
@mdengusiak 

## [gbXML Read Shell Geometry R1.2]( http://www.ladybug.tools/spider/cookbook/gbxml-read-shell-geometry/gbxml-read-shell-geometry.html )

![image](https://user-images.githubusercontent.com/547626/35542358-6e785d54-0514-11e8-9d8d-01ce366ceaf7.png)


## Change Log

R1.2
* Add simplified settings menu

**Comment by mdengusiak** [comment]
@theo-armour 
It was great to talk. As discussed please find attached model with two spaces. 
I added also one window.
 
[RevitTwoSpaces.zip](https://github.com/ladybug-tools/spider/files/1687595/RevitTwoSpaces.zip)

here are one tiny items to fix
1. multiple click on storeys
![image](https://user-images.githubusercontent.com/14005893/35708892-1d3d0200-07a8-11e8-82e2-6df631089cab.png)
