### ISSUE TITLE
export gbxml issue - broken pop up window in cookbook

### ISSUE THREAD

**Issue by chiensiTB** [ladybug-tools/spider#76]
@theo-armour I have fixed this but I need to issue a pull request.  Would you accept one from my fork?

**Comment by theo-armour** [comment]
@chiensiTB 

Please send me a link and I will have a look at the code.

I know that I must expand this:

http://www.ladybug.tools/spider/#pages/contributing.md

And, if nothing else, describe the agree coding style and other intents of this effort.

But for know, it's probably easier to me just to take a look at the code and go on from there.

BTW, are you talking about the following cookbook example?

http://www.ladybug.tools/spider/cookbook/07-create-exportable-buildings/create-exportable-buildings-theo.html

If so, I cannot seem to find a 'broken pop up window' in this example.

**Comment by chiensiTB** [comment]
well, I had made some fixes to your code...

1- i've made it so that a click now closes a window rather than open one on top of the other during your checks prior to download.  I know, moot point, but I hate having to reload the page...

2- I also fixed a few bugs that led to errors in the building area calculation.

https://github.com/chiensiTB/spider/tree/master/cookbook/07-create-exportable-buildings
