### ISSUE TITLE
gbxml export issue: polyloop coordinate ordering is always wrong for roofs

### ISSUE THREAD

**Issue by chiensiTB** [ladybug-tools/spider#77]
I checked a single story building, and found:

Roof polyloops are in the wrong direction.  Using the right hand rule, these polyloops should be oriented away from the volume's interior (outwards).

I find they are always pointing inwards.

**Comment by theo-armour** [comment]
@chiensiTB 

Thank you for having a look.

Can you supply a link to the file in question? I may not have exported all the samples using the latest version of the exporter.

But more important, can you help me establish a test(s) for validating normals. Is there a way of doing something in Open Studio that would help. Currently I just open the file in the Open Studio geometry tab and check the colors.

**Comment by theo-armour** [comment]
@chiensiTB 

I have had a further loo. I can reproduce the error:

![image](https://user-images.githubusercontent.com/547626/35542856-132f92e8-0517-11e8-9cb5-8050ba186413.png)

Normals not visible on top of roof

***

![image](https://user-images.githubusercontent.com/547626/35542900-3809395c-0517-11e8-93b7-2d8fe392c19d.png)

Normals visible on underside of roof

***

I also observe that different footprint types draw the roof normals in different ways. I will try to fix and standardize roof and other slab normals in an upcoming release.

Thanks for the heads-up.

**Comment by chiensiTB** [comment]
Hi @theo-armour 

In my code fork I've fixed this problem.  You can choose to merge my cookbook code with yours, or ping me if you want to discuss further.  My solution is only very basic.

**Comment by theo-armour** [comment]
@chiensiTB 

Can you supply a link to your code?

**Comment by mdengusiak** [comment]
I will close this as no action, respond ... we come back to this later
