### ISSUE TITLE
Update 2018-02-03 ~ gbXML Viewer R9.6 ~ Save Files

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#79]
@ladybug-tools/spiders 

## [gbXML Viewer R9.6]( http://www.ladybug.tools/spider/gbxml-viewer/ )

This first release of Save only saves a copy of the original file.  EditING and saving edits will be added in the near future.

## Change Log

* R9.6a
* Core: add  gbxml var
* Cure: clear divLog with reset view
* Reports: fix issues with storey and space readout in core
* Help text added to Reports menu.
* Save File: first commit
* App: add save file button

**Comment by mdengusiak** [comment]
@theo-armour 
thanks for  Help text this is great :sparkles:
now it is very easy to understand and read though :page_facing_up:
storeys fixed :+1: 
viewer looks amazing now  :boom:

now the next steps ...save... we moving to another level

**Comment by theo-armour** [comment]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/36004194-2f2a3206-0ce6-11e8-891a-0a38b69243aa.png)

## [gbXML Viewer9]( http://www.ladybug.tools/spider/gbxml-viewer/ )

### Better Data Anomaly Checking
In the process of creating its 3D display, gbXML Viewer creates a 3D plane object for every surface in the file. This object is defined by using the first three vertices of the polyloop for each surface. It turns out that gbXML files polyloops may contain a variety of data curiosities. There may be duplicate vertices in the first three vertices - causing a quadrilateral to be created using five vertices instead of just four. Or the first three vertices may be in a straight line. Anything like this will prevent the plane from being well formulated.

The current release add checks for situations like this and uses the fourth vertex instead of the first vertex in order to define the plane. The extra check slows down the loading of the model and ways of mitigating the delay are being investigated.

### HUD
In order to help identify duplicate surfaces or to correct surfaces with duplicate surfaces a variety of new buttons have been added to the heads up display.

The code for deleting duplicates or editing adjacencies will be added in a future release.

## Change Log
* R9.8a
* HUD: Add many new buttons to display
	* ID
	* Type
	* CAD Object ID
	* Spaces
	* Storeys
	* Visibility
	* Duplicate coordinates now highlighted in yellow
* Core: Add checks for duplicate extra vertices in gbXML file vertices data

**Comment by theo-armour** [comment]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/36057447-1d995476-0dc3-11e8-9245-5f40837204fb.png)

## Full screen: [gbXML Viewer9]( http://www.ladybug.tools/spider/gbxml-viewer/ )

## Change Log

* R9.9
* App: Add sucky iOS iframe auto-resize workaround
* HUD:
	* Enable draggable and resizable div
		* Not yet working on mobile devices
	* Fix CADObjectId issue
	* Add volume output
	* Add more console.log outputs
	* Add telltales with vertex numbering

**Comment by theo-armour** [comment]
@mdahlhausen 

Still pre-release...

R10.3
* Many fixes
* Menus move more smoothly
* Editing, deleting and saving all working - but testing has just started
* HUD updates with Editor and reports

**Comment by mdengusiak** [comment]
@theo-armour 
ABSOLUTLEY BRILLIANT!!!!!!!!!!!
first test

model with unwanted shade
![image](https://user-images.githubusercontent.com/14005893/36414807-7a7d15b4-161b-11e8-91e3-45c8e9ba5b35.png)

fix using version R10.3
![image](https://user-images.githubusercontent.com/14005893/36414835-9d52b83c-161b-11e8-8c7b-2cdb84582705.png)

**Comment by mdengusiak** [comment]
One thing to look
I have a correct wall here: 
![image](https://user-images.githubusercontent.com/14005893/36423583-77420932-1638-11e8-8140-0a4dfc12e285.png)

then I had air wall that I corrected as I changed to external wall and connected space.. it is correct on right hand side but when I click using HOD seems to be empty, file is fixed but HOD display is not showing correct data

![image](https://user-images.githubusercontent.com/14005893/36423671-c0bab2bc-1638-11e8-96e9-9bf23a31f70e.png)

**Comment by mdengusiak** [comment]
@theo-armour 
wish list as discussed

1. Allow CADObjectId to be added to Edit: 
![image](https://user-images.githubusercontent.com/14005893/36452191-6f25fad0-168b-11e8-9016-16cf228495f3.png)

2. Allow multiple modification for surfaces with common errors
![image](https://user-images.githubusercontent.com/14005893/36452229-98af85f6-168b-11e8-8f0b-a2531b40e7e0.png)

3. Allow to make few modification before we have to click `save edits`

4. remember set up and view settings after click `save edits` so we have same view and tools open

**Comment by theo-armour** [comment]
@mdengusiak 
2018-02-25 ~ R10.7
Heads-up Display
* Many fixes
* Streamline/simplify the UI

Edit Duplicate Adjacents
* Simplified
* Works more closely with HUD

**Comment by mdengusiak** [comment]
@theo-armour 
thanks a lot,

few urgent fixes reguired

1. In Resport
spaces, surfaces, tiny spaces does not work any more...sth must be disabled

2. Delete Surface from HUD does not work anymore
![image](https://user-images.githubusercontent.com/14005893/36667672-94ba5b06-1ae6-11e8-9f36-f879e655ad6b.png)
