### ISSUE TITLE
Update ~ 2017-09-12 ~ gbXML Viewer 'Harriman'

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#8]
@ladybug-tools/core 

![image](https://user-images.githubusercontent.com/547626/30362245-fc37beea-980f-11e7-93b5-67acd79bfd6d.png)

### Mission

* View gbXML files in 3D in your browser
* Full zoom, pan and rotate
* Run on computer, tablet and phone
* Adjust a wide variety of viewing parameters
* View the full gamut of data typically available in a gbXML file
* Open files via URL or open file dialog
* All free and open source hosted on GitHub

### Vision

* Helping students, clients and non-AEC peeps gain access BIM data easily, quickly and freely

**Comment by mostaphaRoudsari** [comment]
Just wow! It works like a charm.

@saeranv, following up from the conversations last night check this out. @theo-armour also helped Dan to create the viewer for the OpenStudio files. He is simply so good! I have been trying to keep up with his speed and energy and has been failing for the last couple of years. Still trying though... 😄

**Comment by saeranv** [comment]
Thanks @mostaphaRoudsari @theo-armour, we just checked out Dan's OS measure, and this looks really helpful as well.

**Comment by theo-armour** [comment]
@saeranv 

If there's anything I can code for you, do let me know. ;-)
