### ISSUE TITLE
Update 2018-02-04 ~ gbXML Viewer ~ edit file preview

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#80]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/35784186-4331e048-09c9-11e8-8647-25d016ed59c0.png)

## Concept

GbXML file creation is still a young art and the various apps used to create gbXML data - and their users - may create files that contain errors. It may not always be convenient to go back to the app that created the file to fix the errors.

Viewing and locating errors in a gbXML file using a CAD grogram is not always an easy task.

Typical errors we have seen include

* Surfaces assigned to an incorrect surface type
* Surfaces with duplicate interior wall adjacencies
* Duplicate identical surfaces

An app that enables easy viewing of gbXML files, helps with locating and highlighting errors, enables fixing the errors and saving the data to a new file could be a useful addition the designer's toolkit.

### Notes

This script is based on manipulating XML data. The other scripts in the gbXML Viewer series manipulate JSON data extracted from the XML data.

The difference is due to the new and added intention of being able to save an edited version of the XML data to a new file that apart from the edits contains an identical copy of the original XML data.

Other scripts the Spider repo do create building data and save to the gbXML file format, but do not contain shell or rectangular geometry let alone all the other gbXML elements the original file may have contained.

As of this writing, the way forward is not clear. The JSON format used here - which we call gbJSON - has enabled fast, simple relatively easy coding which has produced scripts with many features at a rapid pace.

There are a number of questions:

* Should we ditch gbJSON and learn how to do everything with gbXML - and ignore that more beginner programmers are familiar with JSON than with XML?
* Should we beef up the gbJSOn so that it can read all gbXML data past, present and future and write out new files in canonical gbXML format?
* Can we get the gbXML and the gbJSON to play nice together?

The next few releases should begin to provide some guidance in responding to these questions.

### Mission

* View the IDs of all the surfaces in a list
	* Select the surface you want to edit
* View the names of all the surface types
	* Current surface type of selected surface is highlighted
	* Select a different surface type for the selected surface
* View the IDs of the adjacent spaces
	* Select different spaces for the selected surface

## Wish list

* Highlight the selected surface 'in world' and make other surfaces nearly transparent
* Display the name and CAD ID etc of the selected surface in the menu
* Display the name and CAD ID etc of the selected space(s) in the menu
* Allow you to use all the error-locating tools in the [gbXML Viewer Reports]( http://www.ladybug.tools/spider/gbxml-viewer/r9/gbxml-viewer9-05-reports/test-gbxml-viewer9-reports.html ) script
* **Save the edits to a new file**
	* Perhaps in gbJSON format as well as gbXML

More thoughts

* Add similar editing facilities for storeys, spaces, zones and so on
* Use a similar menu structure to export just portions of a project
* Allow import and export of multiple projects or spaces

## Change Log

* Enable full menu with select elements
* Update Read me

**Comment by theo-armour** [comment]
@ladybug-tools/spiders 

## Full screen: [gbXML Viewer9 Editor Dev R1.2 ]( http://www.ladybug.tools/spider/gbxml-viewer/r9/gbxml-viewer9-11-editor/gbxml-viewer9-core-editor-dev.html )

**Before: surface type is InteriorWall**
![image](https://user-images.githubusercontent.com/547626/35831425-81d30434-0a7e-11e8-8701-306e2e7794be.png)

**After: surface type is Roof**
![image](https://user-images.githubusercontent.com/547626/35831488-b8da1878-0a7e-11e8-90c4-7b815b097e1a.png)

Still to be done
* Editing adjacent spaces
* Fitting all this into the current gbXML viewer - with its error finding reports - and/or creating a new viewer with a different UI


## Change Log

* R1.2
* Tooltip for each select Surface item shows surface name
* Selecting a surface zooms and highlights the surface
* Selecting a surface type updates the surfaces type
* 'view previous update' zooms and highlights the surface previously updated
	* Currently a reset view of the entire building is required - which hides the surface previously edited
	* This could change in the future
* **'save edits' saves the updated data to a new gbXML file**

**Comment by mdengusi** [comment]
@theo-armour 
direction this is heading is absolutely brilliant.... this will be used by everyone who are producing and using  gbXML format .. absolutely excellent! :trophy:
I love selection and zoom in,
can not wait for ability to save fixed files locally so can use it ...

**Comment by theo-armour** [comment]
@mdengusiak 

> can not wait for ability to save fixed files locally so can use it ...

In R1.2 the 'save edits' actually works: it save your edits to a new XML file using the normal file dialog box. Try it!

**Comment by mdengusiak** [comment]
@theo-armour 
this is deafult file...
I open file and found issue and fix it adjacency 1 and 2 was the same aim2449 so I changed adjacency 2 to correct one.. I managed to save but when I open saved file in view could not see this fixed
see atched export file

[aim0016.zip](https://github.com/ladybug-tools/spider/files/1697162/aim0016.zip)



![image](https://user-images.githubusercontent.com/14005893/35833855-d2c7930e-0aca-11e8-83ec-07cd0ab50622.png)


it is still  broken one
![image](https://user-images.githubusercontent.com/14005893/35833948-4d996c9c-0acb-11e8-87a7-4ee84979503d.png)

**Comment by theo-armour** [comment]
@mdengusiak 

In R1.2 updating and saving only works for surface type. 

Adjacencies are for tomorrow. ;-)

**Comment by mdengusiak** [comment]
this is GREAT!!!!!!1

ok I found one example for this
![image](https://user-images.githubusercontent.com/14005893/35834728-ee679664-0ace-11e8-97e8-2493f9c831ed.png)

![image](https://user-images.githubusercontent.com/14005893/35834713-df40e032-0ace-11e8-958d-7baa48c96de0.png)

and then is
![image](https://user-images.githubusercontent.com/14005893/35834828-5963037c-0acf-11e8-80ec-876234d40019.png)

so it works obviously when we assign to roof, ground floor it automatically should make `Adjacency 2 = None`  as default
maybe you can add this ...

**Comment by mdengusiak** [comment]
I found something else this is AMAZING!!!...
my original gbXML file was 48.3 MB when I save after fix is now 23.5 MB
I imported to simulation tool and is fixed now
![image](https://user-images.githubusercontent.com/14005893/35835004-2cfe9f8e-0ad0-11e8-9531-4aa4839ed166.png)

Also I have much less warnings

orignial file
![image](https://user-images.githubusercontent.com/14005893/35835076-8dd89f9e-0ad0-11e8-8bad-ffa7edcadb85.png)

after gbXML import from Revit
![image](https://user-images.githubusercontent.com/14005893/35835128-d3d1a7fc-0ad0-11e8-8f83-82d8fb982453.png)


after fix gbXML import from Tool
![image](https://user-images.githubusercontent.com/14005893/35835053-6b8379a0-0ad0-11e8-9b56-6fc9b5f62ef3.png)

@theo-armour 
this is :rocket:

**Comment by theo-armour** [comment]
@mdengusiak 

> File size and warnings

The browser is being used to convert the text file to XML. I guess that as it does the conversion it finds and fixes errors and deletes spaces etc.

You might experiment with loading an XML file in your browser and saving it to a new file. I think you will find the same fixing and file size reduction happening.

In any case, this was not my doing but is a really nice side benefit.

**Comment by mdengusiak** [comment]
@theo-armour 
definitely
 and also normals are fixed as well.... compare to Revit export

**Comment by mdengusiak** [comment]
@theo-armour 
can we add filter s so can quickly find surface  with issue by typing in addition to scrolling  and fix quickly
![image](https://user-images.githubusercontent.com/26113670/35859179-f7c1bad8-0b36-11e8-9873-ab67189357d3.png)

**Comment by theo-armour** [comment]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/35887358-dca20480-0b48-11e8-800e-c0cdfc64b8d6.png)

## [gbXML Viewer9 Editor Dev]( http://www.ladybug.tools/spider/gbxml-viewer/r9/gbxml-viewer9-11-editor/gbxml-viewer9-core-editor-dev.html )

Looks like we have the beginning of a gbXML Editor

Should this functionality be added to the current Viewer or should this fork into a new stream?

## Change Log

* R1.3
* Add input fields
* Add 'show' buttons
* Add 'update view' button
* Various updates to user experience

**Comment by mdengusiak** [comment]
This is over the top...

can we update ProductName text  :pencil: when we `Save Edits` gbXML? 
we need to be proud and put stamp :)

From : `<ProductName>Autodesk Revit 2018 BEES</ProductName>`
to: `<ProductName>Autodesk Revit 2018 BEES updated by Ladybug Tools Spider gbXML Viewer on 2018.02.07 </ProductName>`

![image](https://user-images.githubusercontent.com/14005893/35936196-76a597bc-0c3a-11e8-9ca1-83294d948a83.png)

**Comment by theo-armour** [comment]
@mdengusiak 

Awesome idea!

The editor is not creating files (yet) so maybe it might be better to add a 'modified' element

http://gbxml.org/schema_doc/6.01/GreenBuildingXML_Ver6.01.html#LinkD1
http://gbxml.org/schema_doc/6.01/GreenBuildingXML_Ver6.01.html#Link15B

Would that be OK?

**Comment by mdengusiak** [comment]
@theo-armour 
sure as long it is our mark :bookmark: is there
