### ISSUE TITLE
export gbxml issue - a surface with openings exports too many coordinates

### ISSUE THREAD

**Issue by chiensiTB** [ladybug-tools/spider#81]
When an opening is added to a surface, effectively "holes" are punched in the surface.  In three.js, this creates extra coordinates for that surface as I believe these are needed to render the surface properly.

However, upon export, most gbxml importers cannot handle these extra coordinates, and should be removed.

@theo-armour I am working on an algorithm to do this, have not nailed it yet.  you may know of a more clever way to do it.  the basic idea is you only want to include the extreme extents of the surface coordinates (the outermost) and throw out all the coordinates created when the openings were punched.  Wonder what you think is the most expedient way to do this.

Idea 1:

- look at the openings defined for the surface.  Use its coordinates and find similar at the surface level, and remove.  Pros:  easy to understand, Cons: could it fail due to floating point errors when comparing coordinates?  

Idead 2:

- take any surface and rotate it onto the x-y plane via transormation matrix / quaternion rotation.  find the extents in the x-y plane (these should now be easy to find since dealing in simple x-y).  Remove all interior coordinates that are within the extents.  Pros:  possibly more robust and possibly quicker (if lots of points).   Cons:  more complicated and still can run into floating point issues if a coordinate is very close to the extents.

**Comment by theo-armour** [comment]
@chiensiTB 

Interesting questions. Without seeing the lines of code you are dealing with, it is difficult to comment.

I find that gbXML and Three.js have very different methods for tackling 3D. I try to keep each in its own set of variables, objects and functions and very, very carefully throw data back and forth over the fence.

 gbXML likes its surfaces to be closed polygons with its openings a multiple separate polygons

Three.js wants you to build a mesh from triangles or it wants you use the 2D Shape geometry with holes and/or a bunch of other ways

Given that you know gbXML far better than Three.js, have you thought of writing directly out to gbXML - and then viewing the result using the gbXMLViewer?

In any case that's how I plan to do things as and when I get back to Build Well.  It might be a bit easier for me to use the gbJSON but writing a utility that creates L, T, H shapes or whatever and spits a gbGXML file should be a piece of cake.

I hope this helps. Do send links to code when you can.

**Comment by chiensiTB** [comment]
This issue has resolved.  I am not sure if there are edge cases, but closed for now.
