### ISSUE TITLE
Cookbook new example ~ multiple objects interactive selection

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#82]
@mdengusiak 

![image](https://user-images.githubusercontent.com/547626/36581953-41740a06-1824-11e8-8cf4-38182ab9bd0e.png)

### [multiple objects interactive selection](  https://rawgit.com/ladybug-tools/spider/master/cookbook/multiple-objects-edit/multiple-objects-interactive-selection.html)

Prototype interface and workflow for editing multiple surfaces in gbXML Viewer

Constraints
* Select and deselect multiple objects
* Update attribute - such as color or type - to selected objects
* Delete selected objects

**Comment by mdengusi** [comment]
@theo-armour  This functionality is exactly what we need ! well done

**Comment by mdengusiak** [comment]
@theo-armour  This functionality is exactly what we need ! well done
