### ISSUE TITLE
gbXML Viewer R11.6 ~ pre-release ~ Save Changes Sample Files

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#85]
@mdengusiak 

Save Changes is a new feature in R11.

## [gbXML Viewer Save Changes Samples Read Me]( http://www.ladybug.tools/spider/index.html#gbxml-sample-files/save-changes-samples/README.md )

This file covers:

* The addition of sample files to experiment with
* An outline of the coding priorities for the next few days

I hope these thoughts help with your testing

**Comment by mdengusiak** [comment]
@theo-armour this is great and clean explanation. I am also focusing on testing saving changes as this is what we normally wil do. 

Here is first problem to solve:
I deleted shade surface and adjusted `Air `to `ExternalWall` and modified `CADObjectID`

![image](https://user-images.githubusercontent.com/14005893/37081482-7b8cd986-21e1-11e8-8875-46960b59531c.png)

All changes are saved apart from  `CADObjectID` it shows as not modifed

![image](https://user-images.githubusercontent.com/14005893/37081493-86adda2c-21e1-11e8-8d45-75180f84753a.png)

I changed again and then click on another surface and back again and here we are is not saving chage:
![image](https://user-images.githubusercontent.com/14005893/37081583-cff9d06e-21e1-11e8-8181-da1b14db7c05.png)

**Comment by theo-armour** [comment]
can you send me the json that did not work?

**Comment by mdengusiak** [comment]
@theo-armour, sure:
[aim0013-changes (2).zip](https://github.com/ladybug-tools/spider/files/1789078/aim0013-changes.2.zip)

**Comment by mdengusiak** [comment]
@theo-armour  tested and works excellent
