### ISSUE TITLE
gbXML Viewer R11.6 ~ pre-release ~ Reports Menu ~ deprecated items

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#86]
@mdengusiak 

## [Reports menu]( http://www.ladybug.tools/spider/gbxml-viewer/r11/gv-rep/gv-rep.html )

This menu currently has two items that are also now in the main menu. Will it be OK to to drop these items in R11?

* Duplicate Adjacencies
* Duplicate Coordinates

**Comment by mdengusiak** [comment]
@theo-armour 
yes, please remove
