### ISSUE TITLE
Update 2018-03-11~ gbXML Viewer R11.12.4 ~ Stable Release

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#87]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/37266797-eeebb38e-2579-11e8-800b-7d37f27cb17a.png)

### gbXML Viewer Features

_The following is a copy of the text in the main [Read Me]( http://www.ladybug.tools/spider/#gbxml-viewer/README.md ). This list of features - like the app itself - is a work-in-progress. There's still quite a few more items to be added._

Open, view and investigate gbXML files in 3D in your browser with free, open source entry-level JavaScript.

### User experience

* Runs in your browser on computer, tablet and phone
* Highly adjustable workspace
* Movable, sliding resizable menus
* View the full gamut of data typically available in a gbXML file
* View gbXML files in 3D
* Full zoom, pan and rotate

### SET Module ~ Settings and Viewing Menu

* Adjust a wide variety of viewing parameters
* Control the appearance of the surfaces
	* Set default, random, Phong default, normal or exposure-type material to all surfaces
	* Update opacity slider
* Control the appearance of the scene
	* Toggle shadows, edges, surface normals
	* Toggle wireframe
	* Toggle gradient background
* Control the content of the scene
	* Toggle axes, grid and ground
* Control the behavior of the scene
	* Toggle scene rotation
	* Toggle perspective and orthographic views
	* Set exploded 3D views
	* Set section Views _work-in-progress_

### REP Module ~ Reports / Data Menu
* View all project textual metadata embedded in gbXML files
* Link to Google map focussed on project latitude and longitude
* Buttons to highlight surfaces, spaces, stories and zones
	* Individually
	* By surface type
	* By individual CAD object IDs
	* By groups of CAD Objects
* Toggle visibility of all items
* Zoom to selected surface or space

### REP Module ~ Reports / Issue tracking Menu

* Identify and inspect programmatically:
	* Duplicate surfaces
	* Surfaces with duplicate adjacent spaces
	* Multiple elements with identical CAD Object ID
	* Tiny surfaces and tiny spaces

Note these REP menu items will evolve into their own ISS issues module in a future release

### HUD Module ~ Heads-up Display / Editing

* Toggle the display of 3D surfaces based on user input
* Highlight and toggle visibility of elements, surfaces, edges
	* Click menu items or use ALT + ZXCV keys
* Click on any surface in the model
	* View id, name, type CAD object id
	* View dimensions and area
	* Delete surface
* Select any surface from scrolling list to see it highlighted on screen and parameters displayed
* Reassign surface type and adjacent spaces for all surfaces
	* View adjacent space parameters
	* Toggle view of space and story
	* Select adjacent spaces from scrolling list
* Save edited data to a new gbXML file with updated document history

### SAV ~ Save Changes

* Save your editing changes to a file for reuse with next incoming gbXML source file update
* Save time with gbXML files that are frequently updated

### CAM Module ~ First person camera Menu
* Optional first person camera enables model fly-through
	* Fly through and around your models.
	* Use cursor keys or WASD keys.
	* Click on the icons at bottom of your screen
	* Use mouse, menu or cursor keys to control full range of motion
	* 3D avatar guides you through space

### ANA Module ~ Sun Path / Analemmas Menu
* Sun path diagrams with analemmas
	Uses Ladybug Tools / Spider Solar Calculator to position Sun correctly for lat/lon at any month, day and hour
* Screen capture to video
	* Currently only on previous release

### GAL Module / Sample gbXML File galleries

* Uses GitHub API to obtain directory listings and load gbXML files in several selected repositories
	* gbXML.org sample files
	* Spider Build Well project files
	* Various files used for testing

***

Behind the scenes:

### APP / THR / COD / GBX ~ the engines that make it all work

* All plain vanilla client-side JavaScript
* Built over the Three.js WebGL JavaScript library
* Uses Showdown to turn Markdown into HTML
* Every menu has own JavaScript file, HTML test file and read me
* Every menu has its own name space and only loads when first called
* Creates gbJSON data for easier processing
* All free and open source and hosted on GitHub
* Open files via open file dialog or drag and drop
* Open files via URL using a link or simply by copying and pasting into the address bar

***

Many thanks to Michal for pushing for all this to happen. May editing gbXML files- one day - be fast and easy.

**Comment by mdengusiak** [comment]
@theo-armour absolutely excellent!

**Comment by theo-armour** [comment]
## Full screen stable release (fingers-crossed) R11.12.5: <http://www.ladybug.tools/spider/gbxml-viewer>

* Fixes issue #90 R11.12 fix surface display to correct storey - but needs careful ongoing checking to verify the fix does not cause issues elsewhere
* Enhancement as per #89 filter files to gbXML only

### Full screen stable release R11.12.4: <br><http://www.ladybug.tools/spider/gbxml-viewer/r11-12-4/gv-app/gv-app.html>

* Just in case there are issues, there is now a link to a full working version of the official stabe relese

#### Full screen development very pre-release R12: <br><http://www.ladybug.tools/spider/gbxml-viewer/dev>

* Still working on simplifying the core to get it to a stage where ~~Mostapha~~ Python coders feel it's OK to hack.

**Comment by mdengusiak** [comment]
Ver 11 is stable and released...we close this now as new R12 is on the way
