### ISSUE TITLE
filter files to gbXML only

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#89]
Can we filter out files to gbXML (.xml) only?

![image](https://user-images.githubusercontent.com/14005893/37331381-ac3e7742-269b-11e8-84cb-ebc06c41f934.png)

**Comment by theo-armour** [comment]
@mdengusiak 

Thanks for the heads-up. Until you asked for this - and I looked into it, I never realized we had control over the default file type to load.

![image](https://user-images.githubusercontent.com/547626/37378825-14f4b5b0-26ee-11e8-90d8-f8fd805b3e56.png)

In gbXML Viewer R11.12.5

**Comment by mdengusiak** [comment]
@theo-armour 
thanks
great, working perfectly..
