### ISSUE TITLE
Update ~ 2017-09-13 ~ gbXML viewer 'carmel'

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#9]
@ladybug-tools/core 

![image](https://user-images.githubusercontent.com/547626/30411517-3a222e46-98c6-11e7-9da0-974573fde9fd.png)

## [gbXML viewer 'carmel']( http://www.ladybug.tools/spider/read-gbxml/gbxml-viewer )

The code is beginning to settle down.Is it time to start thinging about adding new features? Got any good idea?

see also: https://github.com/GreenBuildingXML/Sample-gbXML-Files/issues/3

## Change Log

* gbXML viewer carmel
* App titling automation
* Default menu box has random background gradient
* Select xml cleaned up
* Display gbJSON cleaned up
* Add draw edges
* Getting better: text file viewer

**Comment by mostaphaRoudsari** [comment]
@theo-armour what is the difference between `carmel` and the previous version? Shouldn't it import just any gbXML file?

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Naming things R1, R2, R3 gets to be boring.

I thought it might be fun to give code names to each release.

Is it OK is if the next release has the code name 'mostapha'?
