### ISSUE TITLE
Style Viewer

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#92]
@mdengusiak 

Tool to help you update the gbXML Viewer style sheet colors palette

* Download the Style Viewer HTML file
* Edit the color names in the root section
* Save and reload the web page to view the updates

[Style Viewer]( http://www.ladybug.tools/spider/gbxml-viewer/r12/assets/style-viewer.html )

[Style Viewer Source ]( https://github.com/ladybug-tools/spider/blob/master/gbxml-viewer/r12/assets/style-viewer.html )

**Comment by mdengusiak** [comment]
@theo-armour 
this is great and will really help :) thanks
