### ISSUE TITLE
revit gbxml export inconsistent id's

### ISSUE THREAD

**Issue by arif-hanif** [ladybug-tools/spider#93]
i like the idea of the save changes report, revit has the issue of not generating the same ids on every export.

Any recommendations for this?

**Comment by mdengusiak** [comment]
@arif-hanif 
We are aware with @theo-armour of this behavior. It is really annoying that once any element Revit is changed all IDs in gbXML are recalculated and therefore saved changes can not be used any more as ID are not found. We are thinking about finding different ways to solve it. Right now, it is not easy fix.  I hope we can fix solution in future release.

**Comment by theo-armour** [comment]
@arif-hanif 

Good question.

There may be some workarounds. For example, we could compare a new gbXML file with the previous one and find all the surfaces that has no changes and the surfaces with new information and go on from there.

A good way to start his effort would be to have several very simple before and after gbXML test models. If you can supply some test cases, we could start to have a look at the situation.

**Comment by arif-hanif** [comment]
a comparison for Revit that could work

Space
 - Surface
 - - type, area, CAD object id ( compare these values to generate a diff )

**Comment by mdengusiak** [comment]
@arif-hanif 
thanks for suggestion and idea with solution but this is a bit more complex. 
All CAD object ids could be changed even when one element is model is modified, added or removed. 
So this method would not fully work. 

We need to get surface data  including adjacent `spaces Names` and coordinate for surface vertices  together with current `surface type`, `CADObjectID`, adjacent space Names, exposed to Sun etc... .

Then is a new file we would look for same vertices, find surface and compare all data like: adjacent space Names, Type  etc..

Issue is as you can see we have easy access to ID and then we need to search to get names etc..

![image](https://user-images.githubusercontent.com/14005893/38155844-f16c8294-3471-11e8-8662-8d392d1a38e7.png)

**Comment by theo-armour** [comment]
@arif-hanif @mdengusiak 

Now that a lot of the work on the Reports menu is well under way, I plan to concentrate on the Issue menu for the next few days.

Obviously being able to save changes for reuse is a big item here. So this issue really needs to be dealt with as a priority.

Having said that, I think we are all at a fairly early stage in the learning curve. On trick for early tricky things is to build a simple demo that covers just the specific issue.

In this case I am thinking of a demo that loads two models in two windows, compares the two models and then highlights  the elements that are the same or are different (depending on what you want to see).

Anyway thank you for the tips, I'm sure I will have questions, so watch this space.
