### ISSUE TITLE
CADObject ID ONLY Unique values

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#95]
@theo-armour 
Can we have in list only Unique CADObjectIDs?
Would be much easier to select, thannks

gbXML attached
[MyTestXMLoutput1.zip](https://github.com/ladybug-tools/spider/files/1856604/MyTestXMLoutput1.zip)

![image](https://user-images.githubusercontent.com/14005893/38039694-b9366bf6-32a5-11e8-8ed4-7ebecf734270.png)

2. aslo any idea why we do not see in R12.11 ?
![image](https://user-images.githubusercontent.com/14005893/38041217-19bad996-32a9-11e8-8d1f-bb549197639b.png)

**Comment by theo-armour** [comment]
@mdengusiak 

> Can we have in list only Unique CADObjectIDs?

In other words you would like to see the CAD ID groups only? Just like in the Left Menu?

Will it be OK with TAS and any down stream apps to lose the connection to the original Revit ID?


> Also any idea why we do not see in R12.11 ?
 
I downloaded the file but cannot seem to be able to reproduce the error in R12.13. In any case., it's always a good idea to open the JavaScript console and see if any errors appear - items in the red text.

**Comment by mdengusiak** [comment]
@theo-armour 
as we discussed from R13 we will try to show Group values so data can be applied per type and not instance.

**Comment by theo-armour** [comment]
@mdengusiak 

See Wishlist item

* 2018-04-02 ~ MD/Theo HUD / Heads-Up Display ~ Select from CAD Object types not from entire list

**Comment by mdengusiak** [comment]
@theo-armour 
ok it is now fixed and working in R12.21

![image](https://user-images.githubusercontent.com/14005893/38983656-c0e21eae-43bc-11e8-9341-b4b41f475fba.png)
