### ISSUE TITLE
Polyloop telltales not displaying correctly in R12.11

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#96]
Hi,

Polyloop telltales not displaying correctly. I can not switch on and off them. I can see there is an error on web page. 

![image](https://user-images.githubusercontent.com/14005893/38056990-f128a918-32d5-11e8-8e50-ce90234350ee.png)

**Comment by theo-armour** [comment]
Fixed in R12.14

**Comment by mdengusiak** [comment]
@theo-armour 
working perfect
