### ISSUE TITLE
Hide Right Menu when selection Footer

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#97]
@theo-armour 
tiny item...can we hide `Right Hand Menu` when we select anything from `Footer `so we do not have overlap

![image](https://user-images.githubusercontent.com/14005893/38118385-5443636c-33b2-11e8-92ec-7e784a4e6067.png)

**Comment by theo-armour** [comment]
In R12.13

**Comment by mdengusiak** [comment]
@theo-armour 
working perfect
